/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dao;

import java.util.Date;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;

public interface CreateCitasDao
{
	/**
	 * Method 'execute'
	 * 
	 * @param param
	 * @throws CreateCitasDaoException
	 */
	public void execute(CreateCitasParam param) throws CreateCitasDaoException;

}
