/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dao;

import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;

public interface FormaPagoDao
{
	/** 
	 * Inserts a new row in the FORMA_PAGO table.
	 */
	public FormaPagoPk insert(FormaPago dto) throws FormaPagoDaoException;

	/** 
	 * Updates a single row in the FORMA_PAGO table.
	 */
	public void update(FormaPagoPk pk, FormaPago dto) throws FormaPagoDaoException;

	/** 
	 * Deletes a single row in the FORMA_PAGO table.
	 */
	public void delete(FormaPagoPk pk) throws FormaPagoDaoException;

	/** 
	 * Returns the rows from the FORMA_PAGO table that matches the specified primary-key value.
	 */
	public FormaPago findByPrimaryKey(FormaPagoPk pk) throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the criteria 'ID_FORMA_PAGO = :idFormaPago'.
	 */
	public FormaPago findByPrimaryKey(long idFormaPago) throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the criteria ''.
	 */
	public FormaPago[] findAll() throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the criteria 'ID_FORMA_PAGO = :idFormaPago'.
	 */
	public FormaPago[] findWhereIdFormaPagoEquals(long idFormaPago) throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the criteria 'NOMBRE = :nombre'.
	 */
	public FormaPago[] findWhereNombreEquals(String nombre) throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the criteria 'CANTIDAD_CUOTAS = :cantidadCuotas'.
	 */
	public FormaPago[] findWhereCantidadCuotasEquals(int cantidadCuotas) throws FormaPagoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the specified arbitrary SQL statement
	 */
	public FormaPago[] findByDynamicSelect(String sql, Object[] sqlParams) throws FormaPagoDaoException;

	/** 
	 * Returns all rows from the FORMA_PAGO table that match the specified arbitrary SQL statement
	 */
	public FormaPago[] findByDynamicWhere(String sql, Object[] sqlParams) throws FormaPagoDaoException;

}
