/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dao;

import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;

public interface ReadAllCitasEstadosDao
{
	/**
	 * Method 'execute'
	 * 
	 * @param param
	 * @throws ReadAllCitasEstadosDaoException
	 */
	public void execute(ReadAllCitasEstadosParam param) throws ReadAllCitasEstadosDaoException;

}
