/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ContratoEstadosDaoImpl extends AbstractDAO implements ContratoEstadosDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_CONTRATO_ESTADO, NOMBRE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_CONTRATO_ESTADO, NOMBRE ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_CONTRATO_ESTADO = ?, NOMBRE = ? WHERE ID_CONTRATO_ESTADO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_CONTRATO_ESTADO = ?";

	/** 
	 * Index of column ID_CONTRATO_ESTADO
	 */
	protected static final int COLUMN_ID_CONTRATO_ESTADO = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column ID_CONTRATO_ESTADO
	 */
	protected static final int PK_COLUMN_ID_CONTRATO_ESTADO = 1;

	/** 
	 * Inserts a new row in the CONTRATO_ESTADOS table.
	 */
	public ContratoEstadosPk insert(ContratoEstados dto) throws ContratoEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdContratoEstado() );
			stmt.setString( index++, dto.getNombre() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ContratoEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the CONTRATO_ESTADOS table.
	 */
	public void update(ContratoEstadosPk pk, ContratoEstados dto) throws ContratoEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdContratoEstado() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setLong( 3, pk.getIdContratoEstado() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ContratoEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the CONTRATO_ESTADOS table.
	 */
	public void delete(ContratoEstadosPk pk) throws ContratoEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdContratoEstado() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ContratoEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the CONTRATO_ESTADOS table that matches the specified primary-key value.
	 */
	public ContratoEstados findByPrimaryKey(ContratoEstadosPk pk) throws ContratoEstadosDaoException
	{
		return findByPrimaryKey( pk.getIdContratoEstado() );
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the criteria 'ID_CONTRATO_ESTADO = :idContratoEstado'.
	 */
	public ContratoEstados findByPrimaryKey(long idContratoEstado) throws ContratoEstadosDaoException
	{
		ContratoEstados ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO_ESTADO = ?", new Object[] {  new Long(idContratoEstado) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the criteria ''.
	 */
	public ContratoEstados[] findAll() throws ContratoEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_CONTRATO_ESTADO", null );
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the criteria 'ID_CONTRATO_ESTADO = :idContratoEstado'.
	 */
	public ContratoEstados[] findWhereIdContratoEstadoEquals(long idContratoEstado) throws ContratoEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO_ESTADO = ? ORDER BY ID_CONTRATO_ESTADO", new Object[] {  new Long(idContratoEstado) } );
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the criteria 'NOMBRE = :nombre'.
	 */
	public ContratoEstados[] findWhereNombreEquals(String nombre) throws ContratoEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/**
	 * Method 'ContratoEstadosDaoImpl'
	 * 
	 */
	public ContratoEstadosDaoImpl()
	{
	}

	/**
	 * Method 'ContratoEstadosDaoImpl'
	 * 
	 * @param userConn
	 */
	public ContratoEstadosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.CONTRATO_ESTADOS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ContratoEstados fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ContratoEstados dto = new ContratoEstados();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ContratoEstados[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ContratoEstados dto = new ContratoEstados();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ContratoEstados ret[] = new ContratoEstados[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ContratoEstados dto, ResultSet rs) throws SQLException
	{
		dto.setIdContratoEstado( rs.getLong( COLUMN_ID_CONTRATO_ESTADO ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ContratoEstados dto)
	{
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the specified arbitrary SQL statement
	 */
	public ContratoEstados[] findByDynamicSelect(String sql, Object[] sqlParams) throws ContratoEstadosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ContratoEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the CONTRATO_ESTADOS table that match the specified arbitrary SQL statement
	 */
	public ContratoEstados[] findByDynamicWhere(String sql, Object[] sqlParams) throws ContratoEstadosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ContratoEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
