/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DocEstadosDaoImpl extends AbstractDAO implements DocEstadosDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_ESTADO_DOC, NOMBRE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_ESTADO_DOC, NOMBRE ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_ESTADO_DOC = ?, NOMBRE = ? WHERE ID_ESTADO_DOC = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_ESTADO_DOC = ?";

	/** 
	 * Index of column ID_ESTADO_DOC
	 */
	protected static final int COLUMN_ID_ESTADO_DOC = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column ID_ESTADO_DOC
	 */
	protected static final int PK_COLUMN_ID_ESTADO_DOC = 1;

	/** 
	 * Inserts a new row in the DOC_ESTADOS table.
	 */
	public DocEstadosPk insert(DocEstados dto) throws DocEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdEstadoDoc() );
			stmt.setString( index++, dto.getNombre() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the DOC_ESTADOS table.
	 */
	public void update(DocEstadosPk pk, DocEstados dto) throws DocEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdEstadoDoc() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setLong( 3, pk.getIdEstadoDoc() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the DOC_ESTADOS table.
	 */
	public void delete(DocEstadosPk pk) throws DocEstadosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdEstadoDoc() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the DOC_ESTADOS table that matches the specified primary-key value.
	 */
	public DocEstados findByPrimaryKey(DocEstadosPk pk) throws DocEstadosDaoException
	{
		return findByPrimaryKey( pk.getIdEstadoDoc() );
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the criteria 'ID_ESTADO_DOC = :idEstadoDoc'.
	 */
	public DocEstados findByPrimaryKey(long idEstadoDoc) throws DocEstadosDaoException
	{
		DocEstados ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTADO_DOC = ?", new Object[] {  new Long(idEstadoDoc) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the criteria ''.
	 */
	public DocEstados[] findAll() throws DocEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_ESTADO_DOC", null );
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the criteria 'ID_ESTADO_DOC = :idEstadoDoc'.
	 */
	public DocEstados[] findWhereIdEstadoDocEquals(long idEstadoDoc) throws DocEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTADO_DOC = ? ORDER BY ID_ESTADO_DOC", new Object[] {  new Long(idEstadoDoc) } );
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the criteria 'NOMBRE = :nombre'.
	 */
	public DocEstados[] findWhereNombreEquals(String nombre) throws DocEstadosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/**
	 * Method 'DocEstadosDaoImpl'
	 * 
	 */
	public DocEstadosDaoImpl()
	{
	}

	/**
	 * Method 'DocEstadosDaoImpl'
	 * 
	 * @param userConn
	 */
	public DocEstadosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.DOC_ESTADOS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected DocEstados fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			DocEstados dto = new DocEstados();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected DocEstados[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			DocEstados dto = new DocEstados();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		DocEstados ret[] = new DocEstados[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(DocEstados dto, ResultSet rs) throws SQLException
	{
		dto.setIdEstadoDoc( rs.getLong( COLUMN_ID_ESTADO_DOC ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(DocEstados dto)
	{
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the specified arbitrary SQL statement
	 */
	public DocEstados[] findByDynamicSelect(String sql, Object[] sqlParams) throws DocEstadosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the DOC_ESTADOS table that match the specified arbitrary SQL statement
	 */
	public DocEstados[] findByDynamicWhere(String sql, Object[] sqlParams) throws DocEstadosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocEstadosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
