/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import java.util.Date;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DocumentosDaoImpl extends AbstractDAO implements DocumentosDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_DOCUMENTO, URL, CREADO, ID_CONTRATO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_DOCUMENTO, URL, CREADO, ID_CONTRATO ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_DOCUMENTO = ?, URL = ?, CREADO = ?, ID_CONTRATO = ? WHERE ID_DOCUMENTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_DOCUMENTO = ?";

	/** 
	 * Index of column ID_DOCUMENTO
	 */
	protected static final int COLUMN_ID_DOCUMENTO = 1;

	/** 
	 * Index of column URL
	 */
	protected static final int COLUMN_URL = 2;

	/** 
	 * Index of column CREADO
	 */
	protected static final int COLUMN_CREADO = 3;

	/** 
	 * Index of column ID_CONTRATO
	 */
	protected static final int COLUMN_ID_CONTRATO = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ID_DOCUMENTO
	 */
	protected static final int PK_COLUMN_ID_DOCUMENTO = 1;

	/** 
	 * Inserts a new row in the DOCUMENTOS table.
	 */
	public DocumentosPk insert(Documentos dto) throws DocumentosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdDocumento() );
			stmt.setString( index++, dto.getUrl() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setLong( index++, dto.getIdContrato() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the DOCUMENTOS table.
	 */
	public void update(DocumentosPk pk, Documentos dto) throws DocumentosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdDocumento() );
			stmt.setString( index++, dto.getUrl() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setLong( index++, dto.getIdContrato() );
			stmt.setLong( 5, pk.getIdDocumento() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the DOCUMENTOS table.
	 */
	public void delete(DocumentosPk pk) throws DocumentosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdDocumento() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the DOCUMENTOS table that matches the specified primary-key value.
	 */
	public Documentos findByPrimaryKey(DocumentosPk pk) throws DocumentosDaoException
	{
		return findByPrimaryKey( pk.getIdDocumento() );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'ID_DOCUMENTO = :idDocumento'.
	 */
	public Documentos findByPrimaryKey(long idDocumento) throws DocumentosDaoException
	{
		Documentos ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_DOCUMENTO = ?", new Object[] {  new Long(idDocumento) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria ''.
	 */
	public Documentos[] findAll() throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_DOCUMENTO", null );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'ID_CONTRATO = :idContrato'.
	 */
	public Documentos[] findByContratos(long idContrato) throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO = ?", new Object[] {  new Long(idContrato) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'ID_DOCUMENTO = :idDocumento'.
	 */
	public Documentos[] findWhereIdDocumentoEquals(long idDocumento) throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_DOCUMENTO = ? ORDER BY ID_DOCUMENTO", new Object[] {  new Long(idDocumento) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'URL = :url'.
	 */
	public Documentos[] findWhereUrlEquals(String url) throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE URL = ? ORDER BY URL", new Object[] { url } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'CREADO = :creado'.
	 */
	public Documentos[] findWhereCreadoEquals(Date creado) throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CREADO = ? ORDER BY CREADO", new Object[] { creado==null ? null : new java.sql.Timestamp( creado.getTime() ) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the criteria 'ID_CONTRATO = :idContrato'.
	 */
	public Documentos[] findWhereIdContratoEquals(long idContrato) throws DocumentosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO = ? ORDER BY ID_CONTRATO", new Object[] {  new Long(idContrato) } );
	}

	/**
	 * Method 'DocumentosDaoImpl'
	 * 
	 */
	public DocumentosDaoImpl()
	{
	}

	/**
	 * Method 'DocumentosDaoImpl'
	 * 
	 * @param userConn
	 */
	public DocumentosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.DOCUMENTOS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Documentos fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Documentos dto = new Documentos();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Documentos[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Documentos dto = new Documentos();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Documentos ret[] = new Documentos[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Documentos dto, ResultSet rs) throws SQLException
	{
		dto.setIdDocumento( rs.getLong( COLUMN_ID_DOCUMENTO ) );
		dto.setUrl( rs.getString( COLUMN_URL ) );
		dto.setCreado( rs.getTimestamp(COLUMN_CREADO ) );
		dto.setIdContrato( rs.getLong( COLUMN_ID_CONTRATO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Documentos dto)
	{
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the specified arbitrary SQL statement
	 */
	public Documentos[] findByDynamicSelect(String sql, Object[] sqlParams) throws DocumentosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the DOCUMENTOS table that match the specified arbitrary SQL statement
	 */
	public Documentos[] findByDynamicWhere(String sql, Object[] sqlParams) throws DocumentosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
