/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import java.util.Date;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DocumentosCitasDaoImpl extends AbstractDAO implements DocumentosCitasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_CITA, ID_DOCUMENTO, ID_ESTADO_DOC, CREADO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_CITA, ID_DOCUMENTO, ID_ESTADO_DOC, CREADO ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_CITA = ?, ID_DOCUMENTO = ?, ID_ESTADO_DOC = ?, CREADO = ? WHERE ID_CITA = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_CITA = ?";

	/** 
	 * Index of column ID_CITA
	 */
	protected static final int COLUMN_ID_CITA = 1;

	/** 
	 * Index of column ID_DOCUMENTO
	 */
	protected static final int COLUMN_ID_DOCUMENTO = 2;

	/** 
	 * Index of column ID_ESTADO_DOC
	 */
	protected static final int COLUMN_ID_ESTADO_DOC = 3;

	/** 
	 * Index of column CREADO
	 */
	protected static final int COLUMN_CREADO = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ID_CITA
	 */
	protected static final int PK_COLUMN_ID_CITA = 1;

	/** 
	 * Inserts a new row in the DOCUMENTOS_CITAS table.
	 */
	public DocumentosCitasPk insert(DocumentosCitas dto) throws DocumentosCitasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdCita() );
			stmt.setLong( index++, dto.getIdDocumento() );
			stmt.setLong( index++, dto.getIdEstadoDoc() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosCitasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the DOCUMENTOS_CITAS table.
	 */
	public void update(DocumentosCitasPk pk, DocumentosCitas dto) throws DocumentosCitasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdCita() );
			stmt.setLong( index++, dto.getIdDocumento() );
			stmt.setLong( index++, dto.getIdEstadoDoc() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setLong( 5, pk.getIdCita() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosCitasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the DOCUMENTOS_CITAS table.
	 */
	public void delete(DocumentosCitasPk pk) throws DocumentosCitasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdCita() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosCitasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the DOCUMENTOS_CITAS table that matches the specified primary-key value.
	 */
	public DocumentosCitas findByPrimaryKey(DocumentosCitasPk pk) throws DocumentosCitasDaoException
	{
		return findByPrimaryKey( pk.getIdCita() );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_CITA = :idCita'.
	 */
	public DocumentosCitas findByPrimaryKey(long idCita) throws DocumentosCitasDaoException
	{
		DocumentosCitas ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_CITA = ?", new Object[] {  new Long(idCita) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria ''.
	 */
	public DocumentosCitas[] findAll() throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_CITA", null );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_CITA = :idCita'.
	 */
	public DocumentosCitas[] findByCitas(long idCita) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CITA = ?", new Object[] {  new Long(idCita) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_ESTADO_DOC = :idEstadoDoc'.
	 */
	public DocumentosCitas[] findByDocEstados(long idEstadoDoc) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTADO_DOC = ?", new Object[] {  new Long(idEstadoDoc) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_DOCUMENTO = :idDocumento'.
	 */
	public DocumentosCitas[] findByDocumentos(long idDocumento) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_DOCUMENTO = ?", new Object[] {  new Long(idDocumento) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_CITA = :idCita'.
	 */
	public DocumentosCitas[] findWhereIdCitaEquals(long idCita) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CITA = ? ORDER BY ID_CITA", new Object[] {  new Long(idCita) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_DOCUMENTO = :idDocumento'.
	 */
	public DocumentosCitas[] findWhereIdDocumentoEquals(long idDocumento) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_DOCUMENTO = ? ORDER BY ID_DOCUMENTO", new Object[] {  new Long(idDocumento) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'ID_ESTADO_DOC = :idEstadoDoc'.
	 */
	public DocumentosCitas[] findWhereIdEstadoDocEquals(long idEstadoDoc) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTADO_DOC = ? ORDER BY ID_ESTADO_DOC", new Object[] {  new Long(idEstadoDoc) } );
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the criteria 'CREADO = :creado'.
	 */
	public DocumentosCitas[] findWhereCreadoEquals(Date creado) throws DocumentosCitasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CREADO = ? ORDER BY CREADO", new Object[] { creado==null ? null : new java.sql.Timestamp( creado.getTime() ) } );
	}

	/**
	 * Method 'DocumentosCitasDaoImpl'
	 * 
	 */
	public DocumentosCitasDaoImpl()
	{
	}

	/**
	 * Method 'DocumentosCitasDaoImpl'
	 * 
	 * @param userConn
	 */
	public DocumentosCitasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.DOCUMENTOS_CITAS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected DocumentosCitas fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			DocumentosCitas dto = new DocumentosCitas();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected DocumentosCitas[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			DocumentosCitas dto = new DocumentosCitas();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		DocumentosCitas ret[] = new DocumentosCitas[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(DocumentosCitas dto, ResultSet rs) throws SQLException
	{
		dto.setIdCita( rs.getLong( COLUMN_ID_CITA ) );
		dto.setIdDocumento( rs.getLong( COLUMN_ID_DOCUMENTO ) );
		dto.setIdEstadoDoc( rs.getLong( COLUMN_ID_ESTADO_DOC ) );
		dto.setCreado( rs.getTimestamp(COLUMN_CREADO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(DocumentosCitas dto)
	{
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the specified arbitrary SQL statement
	 */
	public DocumentosCitas[] findByDynamicSelect(String sql, Object[] sqlParams) throws DocumentosCitasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosCitasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the DOCUMENTOS_CITAS table that match the specified arbitrary SQL statement
	 */
	public DocumentosCitas[] findByDynamicWhere(String sql, Object[] sqlParams) throws DocumentosCitasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DocumentosCitasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
