/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import java.util.Date;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class NotariasDaoImpl extends AbstractDAO implements NotariasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_NOTARIA, NOMBRE, RAZON_SOCIAL, DIRECCION, TELEFONO, ID_COMUNA, CREADO, MODIFICADO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_NOTARIA, NOMBRE, RAZON_SOCIAL, DIRECCION, TELEFONO, ID_COMUNA, CREADO, MODIFICADO ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_NOTARIA = ?, NOMBRE = ?, RAZON_SOCIAL = ?, DIRECCION = ?, TELEFONO = ?, ID_COMUNA = ?, CREADO = ?, MODIFICADO = ? WHERE ID_NOTARIA = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_NOTARIA = ?";

	/** 
	 * Index of column ID_NOTARIA
	 */
	protected static final int COLUMN_ID_NOTARIA = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column RAZON_SOCIAL
	 */
	protected static final int COLUMN_RAZON_SOCIAL = 3;

	/** 
	 * Index of column DIRECCION
	 */
	protected static final int COLUMN_DIRECCION = 4;

	/** 
	 * Index of column TELEFONO
	 */
	protected static final int COLUMN_TELEFONO = 5;

	/** 
	 * Index of column ID_COMUNA
	 */
	protected static final int COLUMN_ID_COMUNA = 6;

	/** 
	 * Index of column CREADO
	 */
	protected static final int COLUMN_CREADO = 7;

	/** 
	 * Index of column MODIFICADO
	 */
	protected static final int COLUMN_MODIFICADO = 8;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 8;

	/** 
	 * Index of primary-key column ID_NOTARIA
	 */
	protected static final int PK_COLUMN_ID_NOTARIA = 1;

	/** 
	 * Inserts a new row in the NOTARIAS table.
	 */
	public NotariasPk insert(Notarias dto) throws NotariasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdNotaria() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getRazonSocial() );
			stmt.setString( index++, dto.getDireccion() );
			if (dto.isTelefonoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getTelefono() );
			}
		
			if (dto.isIdComunaNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getIdComuna() );
			}
		
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setTimestamp(index++, dto.getModificado()==null ? null : new java.sql.Timestamp( dto.getModificado().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NotariasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the NOTARIAS table.
	 */
	public void update(NotariasPk pk, Notarias dto) throws NotariasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdNotaria() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getRazonSocial() );
			stmt.setString( index++, dto.getDireccion() );
			if (dto.isTelefonoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getTelefono() );
			}
		
			if (dto.isIdComunaNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getIdComuna() );
			}
		
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setTimestamp(index++, dto.getModificado()==null ? null : new java.sql.Timestamp( dto.getModificado().getTime() ) );
			stmt.setLong( 9, pk.getIdNotaria() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NotariasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the NOTARIAS table.
	 */
	public void delete(NotariasPk pk) throws NotariasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdNotaria() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NotariasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the NOTARIAS table that matches the specified primary-key value.
	 */
	public Notarias findByPrimaryKey(NotariasPk pk) throws NotariasDaoException
	{
		return findByPrimaryKey( pk.getIdNotaria() );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'ID_NOTARIA = :idNotaria'.
	 */
	public Notarias findByPrimaryKey(long idNotaria) throws NotariasDaoException
	{
		Notarias ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_NOTARIA = ?", new Object[] {  new Long(idNotaria) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria ''.
	 */
	public Notarias[] findAll() throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_NOTARIA", null );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'ID_COMUNA = :idComuna'.
	 */
	public Notarias[] findByComuna(long idComuna) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_COMUNA = ?", new Object[] {  new Long(idComuna) } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'ID_NOTARIA = :idNotaria'.
	 */
	public Notarias[] findWhereIdNotariaEquals(long idNotaria) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_NOTARIA = ? ORDER BY ID_NOTARIA", new Object[] {  new Long(idNotaria) } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Notarias[] findWhereNombreEquals(String nombre) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'RAZON_SOCIAL = :razonSocial'.
	 */
	public Notarias[] findWhereRazonSocialEquals(String razonSocial) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE RAZON_SOCIAL = ? ORDER BY RAZON_SOCIAL", new Object[] { razonSocial } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'DIRECCION = :direccion'.
	 */
	public Notarias[] findWhereDireccionEquals(String direccion) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DIRECCION = ? ORDER BY DIRECCION", new Object[] { direccion } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'TELEFONO = :telefono'.
	 */
	public Notarias[] findWhereTelefonoEquals(long telefono) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TELEFONO = ? ORDER BY TELEFONO", new Object[] {  new Long(telefono) } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'ID_COMUNA = :idComuna'.
	 */
	public Notarias[] findWhereIdComunaEquals(long idComuna) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_COMUNA = ? ORDER BY ID_COMUNA", new Object[] {  new Long(idComuna) } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'CREADO = :creado'.
	 */
	public Notarias[] findWhereCreadoEquals(Date creado) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CREADO = ? ORDER BY CREADO", new Object[] { creado==null ? null : new java.sql.Timestamp( creado.getTime() ) } );
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the criteria 'MODIFICADO = :modificado'.
	 */
	public Notarias[] findWhereModificadoEquals(Date modificado) throws NotariasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MODIFICADO = ? ORDER BY MODIFICADO", new Object[] { modificado==null ? null : new java.sql.Timestamp( modificado.getTime() ) } );
	}

	/**
	 * Method 'NotariasDaoImpl'
	 * 
	 */
	public NotariasDaoImpl()
	{
	}

	/**
	 * Method 'NotariasDaoImpl'
	 * 
	 * @param userConn
	 */
	public NotariasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.NOTARIAS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Notarias fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Notarias dto = new Notarias();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Notarias[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Notarias dto = new Notarias();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Notarias ret[] = new Notarias[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Notarias dto, ResultSet rs) throws SQLException
	{
		dto.setIdNotaria( rs.getLong( COLUMN_ID_NOTARIA ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setRazonSocial( rs.getString( COLUMN_RAZON_SOCIAL ) );
		dto.setDireccion( rs.getString( COLUMN_DIRECCION ) );
		dto.setTelefono( rs.getLong( COLUMN_TELEFONO ) );
		if (rs.wasNull()) {
			dto.setTelefonoNull( true );
		}
		
		dto.setIdComuna( rs.getLong( COLUMN_ID_COMUNA ) );
		if (rs.wasNull()) {
			dto.setIdComunaNull( true );
		}
		
		dto.setCreado( rs.getTimestamp(COLUMN_CREADO ) );
		dto.setModificado( rs.getTimestamp(COLUMN_MODIFICADO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Notarias dto)
	{
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the specified arbitrary SQL statement
	 */
	public Notarias[] findByDynamicSelect(String sql, Object[] sqlParams) throws NotariasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NotariasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the NOTARIAS table that match the specified arbitrary SQL statement
	 */
	public Notarias[] findByDynamicWhere(String sql, Object[] sqlParams) throws NotariasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NotariasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
