/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import java.util.Date;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PagosDaoImpl extends AbstractDAO implements PagosDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_PAGO, FECHA_HORA, MONTO, CREADO, MODIFICADO, ID_CONTRATO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_PAGO, FECHA_HORA, MONTO, CREADO, MODIFICADO, ID_CONTRATO ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_PAGO = ?, FECHA_HORA = ?, MONTO = ?, CREADO = ?, MODIFICADO = ?, ID_CONTRATO = ? WHERE ID_PAGO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_PAGO = ?";

	/** 
	 * Index of column ID_PAGO
	 */
	protected static final int COLUMN_ID_PAGO = 1;

	/** 
	 * Index of column FECHA_HORA
	 */
	protected static final int COLUMN_FECHA_HORA = 2;

	/** 
	 * Index of column MONTO
	 */
	protected static final int COLUMN_MONTO = 3;

	/** 
	 * Index of column CREADO
	 */
	protected static final int COLUMN_CREADO = 4;

	/** 
	 * Index of column MODIFICADO
	 */
	protected static final int COLUMN_MODIFICADO = 5;

	/** 
	 * Index of column ID_CONTRATO
	 */
	protected static final int COLUMN_ID_CONTRATO = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column ID_PAGO
	 */
	protected static final int PK_COLUMN_ID_PAGO = 1;

	/** 
	 * Inserts a new row in the PAGOS table.
	 */
	public PagosPk insert(Pagos dto) throws PagosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdPago() );
			stmt.setTimestamp(index++, dto.getFechaHora()==null ? null : new java.sql.Timestamp( dto.getFechaHora().getTime() ) );
			stmt.setLong( index++, dto.getMonto() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setTimestamp(index++, dto.getModificado()==null ? null : new java.sql.Timestamp( dto.getModificado().getTime() ) );
			if (dto.isIdContratoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getIdContrato() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PagosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the PAGOS table.
	 */
	public void update(PagosPk pk, Pagos dto) throws PagosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdPago() );
			stmt.setTimestamp(index++, dto.getFechaHora()==null ? null : new java.sql.Timestamp( dto.getFechaHora().getTime() ) );
			stmt.setLong( index++, dto.getMonto() );
			stmt.setTimestamp(index++, dto.getCreado()==null ? null : new java.sql.Timestamp( dto.getCreado().getTime() ) );
			stmt.setTimestamp(index++, dto.getModificado()==null ? null : new java.sql.Timestamp( dto.getModificado().getTime() ) );
			if (dto.isIdContratoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getIdContrato() );
			}
		
			stmt.setLong( 7, pk.getIdPago() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PagosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the PAGOS table.
	 */
	public void delete(PagosPk pk) throws PagosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdPago() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PagosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the PAGOS table that matches the specified primary-key value.
	 */
	public Pagos findByPrimaryKey(PagosPk pk) throws PagosDaoException
	{
		return findByPrimaryKey( pk.getIdPago() );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'ID_PAGO = :idPago'.
	 */
	public Pagos findByPrimaryKey(long idPago) throws PagosDaoException
	{
		Pagos ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_PAGO = ?", new Object[] {  new Long(idPago) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria ''.
	 */
	public Pagos[] findAll() throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_PAGO", null );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'ID_CONTRATO = :idContrato'.
	 */
	public Pagos[] findByContratos(long idContrato) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO = ?", new Object[] {  new Long(idContrato) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'ID_PAGO = :idPago'.
	 */
	public Pagos[] findWhereIdPagoEquals(long idPago) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_PAGO = ? ORDER BY ID_PAGO", new Object[] {  new Long(idPago) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'FECHA_HORA = :fechaHora'.
	 */
	public Pagos[] findWhereFechaHoraEquals(Date fechaHora) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_HORA = ? ORDER BY FECHA_HORA", new Object[] { fechaHora==null ? null : new java.sql.Timestamp( fechaHora.getTime() ) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'MONTO = :monto'.
	 */
	public Pagos[] findWhereMontoEquals(long monto) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MONTO = ? ORDER BY MONTO", new Object[] {  new Long(monto) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'CREADO = :creado'.
	 */
	public Pagos[] findWhereCreadoEquals(Date creado) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CREADO = ? ORDER BY CREADO", new Object[] { creado==null ? null : new java.sql.Timestamp( creado.getTime() ) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'MODIFICADO = :modificado'.
	 */
	public Pagos[] findWhereModificadoEquals(Date modificado) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MODIFICADO = ? ORDER BY MODIFICADO", new Object[] { modificado==null ? null : new java.sql.Timestamp( modificado.getTime() ) } );
	}

	/** 
	 * Returns all rows from the PAGOS table that match the criteria 'ID_CONTRATO = :idContrato'.
	 */
	public Pagos[] findWhereIdContratoEquals(long idContrato) throws PagosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CONTRATO = ? ORDER BY ID_CONTRATO", new Object[] {  new Long(idContrato) } );
	}

	/**
	 * Method 'PagosDaoImpl'
	 * 
	 */
	public PagosDaoImpl()
	{
	}

	/**
	 * Method 'PagosDaoImpl'
	 * 
	 * @param userConn
	 */
	public PagosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.PAGOS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Pagos fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Pagos dto = new Pagos();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Pagos[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Pagos dto = new Pagos();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Pagos ret[] = new Pagos[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Pagos dto, ResultSet rs) throws SQLException
	{
		dto.setIdPago( rs.getLong( COLUMN_ID_PAGO ) );
		dto.setFechaHora( rs.getTimestamp(COLUMN_FECHA_HORA ) );
		dto.setMonto( rs.getLong( COLUMN_MONTO ) );
		dto.setCreado( rs.getTimestamp(COLUMN_CREADO ) );
		dto.setModificado( rs.getTimestamp(COLUMN_MODIFICADO ) );
		dto.setIdContrato( rs.getLong( COLUMN_ID_CONTRATO ) );
		if (rs.wasNull()) {
			dto.setIdContratoNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Pagos dto)
	{
	}

	/** 
	 * Returns all rows from the PAGOS table that match the specified arbitrary SQL statement
	 */
	public Pagos[] findByDynamicSelect(String sql, Object[] sqlParams) throws PagosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PagosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the PAGOS table that match the specified arbitrary SQL statement
	 */
	public Pagos[] findByDynamicWhere(String sql, Object[] sqlParams) throws PagosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PagosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
