/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.jdbc;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.dto.*;
import com.Abogados.Lex.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PresupuestoDetallesDaoImpl extends AbstractDAO implements PresupuestoDetallesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_DETALLE_PRESUPUESTO, SERVICIO, MONTO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_DETALLE_PRESUPUESTO, SERVICIO, MONTO ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_DETALLE_PRESUPUESTO = ?, SERVICIO = ?, MONTO = ? WHERE ID_DETALLE_PRESUPUESTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_DETALLE_PRESUPUESTO = ?";

	/** 
	 * Index of column ID_DETALLE_PRESUPUESTO
	 */
	protected static final int COLUMN_ID_DETALLE_PRESUPUESTO = 1;

	/** 
	 * Index of column SERVICIO
	 */
	protected static final int COLUMN_SERVICIO = 2;

	/** 
	 * Index of column MONTO
	 */
	protected static final int COLUMN_MONTO = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column ID_DETALLE_PRESUPUESTO
	 */
	protected static final int PK_COLUMN_ID_DETALLE_PRESUPUESTO = 1;

	/** 
	 * Inserts a new row in the PRESUPUESTO_DETALLES table.
	 */
	public PresupuestoDetallesPk insert(PresupuestoDetalles dto) throws PresupuestoDetallesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIdDetallePresupuesto() );
			stmt.setString( index++, dto.getServicio() );
			stmt.setLong( index++, dto.getMonto() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PresupuestoDetallesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the PRESUPUESTO_DETALLES table.
	 */
	public void update(PresupuestoDetallesPk pk, PresupuestoDetalles dto) throws PresupuestoDetallesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIdDetallePresupuesto() );
			stmt.setString( index++, dto.getServicio() );
			stmt.setLong( index++, dto.getMonto() );
			stmt.setLong( 4, pk.getIdDetallePresupuesto() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PresupuestoDetallesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the PRESUPUESTO_DETALLES table.
	 */
	public void delete(PresupuestoDetallesPk pk) throws PresupuestoDetallesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdDetallePresupuesto() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PresupuestoDetallesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the PRESUPUESTO_DETALLES table that matches the specified primary-key value.
	 */
	public PresupuestoDetalles findByPrimaryKey(PresupuestoDetallesPk pk) throws PresupuestoDetallesDaoException
	{
		return findByPrimaryKey( pk.getIdDetallePresupuesto() );
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the criteria 'ID_DETALLE_PRESUPUESTO = :idDetallePresupuesto'.
	 */
	public PresupuestoDetalles findByPrimaryKey(long idDetallePresupuesto) throws PresupuestoDetallesDaoException
	{
		PresupuestoDetalles ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_DETALLE_PRESUPUESTO = ?", new Object[] {  new Long(idDetallePresupuesto) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the criteria ''.
	 */
	public PresupuestoDetalles[] findAll() throws PresupuestoDetallesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_DETALLE_PRESUPUESTO", null );
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the criteria 'ID_DETALLE_PRESUPUESTO = :idDetallePresupuesto'.
	 */
	public PresupuestoDetalles[] findWhereIdDetallePresupuestoEquals(long idDetallePresupuesto) throws PresupuestoDetallesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_DETALLE_PRESUPUESTO = ? ORDER BY ID_DETALLE_PRESUPUESTO", new Object[] {  new Long(idDetallePresupuesto) } );
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the criteria 'SERVICIO = :servicio'.
	 */
	public PresupuestoDetalles[] findWhereServicioEquals(String servicio) throws PresupuestoDetallesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SERVICIO = ? ORDER BY SERVICIO", new Object[] { servicio } );
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the criteria 'MONTO = :monto'.
	 */
	public PresupuestoDetalles[] findWhereMontoEquals(long monto) throws PresupuestoDetallesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MONTO = ? ORDER BY MONTO", new Object[] {  new Long(monto) } );
	}

	/**
	 * Method 'PresupuestoDetallesDaoImpl'
	 * 
	 */
	public PresupuestoDetallesDaoImpl()
	{
	}

	/**
	 * Method 'PresupuestoDetallesDaoImpl'
	 * 
	 * @param userConn
	 */
	public PresupuestoDetallesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "LEX.PRESUPUESTO_DETALLES";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PresupuestoDetalles fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PresupuestoDetalles dto = new PresupuestoDetalles();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PresupuestoDetalles[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PresupuestoDetalles dto = new PresupuestoDetalles();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PresupuestoDetalles ret[] = new PresupuestoDetalles[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PresupuestoDetalles dto, ResultSet rs) throws SQLException
	{
		dto.setIdDetallePresupuesto( rs.getLong( COLUMN_ID_DETALLE_PRESUPUESTO ) );
		dto.setServicio( rs.getString( COLUMN_SERVICIO ) );
		dto.setMonto( rs.getLong( COLUMN_MONTO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PresupuestoDetalles dto)
	{
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the specified arbitrary SQL statement
	 */
	public PresupuestoDetalles[] findByDynamicSelect(String sql, Object[] sqlParams) throws PresupuestoDetallesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PresupuestoDetallesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the PRESUPUESTO_DETALLES table that match the specified arbitrary SQL statement
	 */
	public PresupuestoDetalles[] findByDynamicWhere(String sql, Object[] sqlParams) throws PresupuestoDetallesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PresupuestoDetallesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
