/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CITA_ESTADOS table.
 */
public class CitaEstadosPk implements Serializable
{
	protected long idEstadoCita;

	/** 
	 * This attribute represents whether the primitive attribute idEstadoCita is null.
	 */
	protected boolean idEstadoCitaNull;

	/** 
	 * Sets the value of idEstadoCita
	 */
	public void setIdEstadoCita(long idEstadoCita)
	{
		this.idEstadoCita = idEstadoCita;
	}

	/** 
	 * Gets the value of idEstadoCita
	 */
	public long getIdEstadoCita()
	{
		return idEstadoCita;
	}

	/**
	 * Method 'CitaEstadosPk'
	 * 
	 */
	public CitaEstadosPk()
	{
	}

	/**
	 * Method 'CitaEstadosPk'
	 * 
	 * @param idEstadoCita
	 */
	public CitaEstadosPk(final long idEstadoCita)
	{
		this.idEstadoCita = idEstadoCita;
	}

	/** 
	 * Sets the value of idEstadoCitaNull
	 */
	public void setIdEstadoCitaNull(boolean idEstadoCitaNull)
	{
		this.idEstadoCitaNull = idEstadoCitaNull;
	}

	/** 
	 * Gets the value of idEstadoCitaNull
	 */
	public boolean isIdEstadoCitaNull()
	{
		return idEstadoCitaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CitaEstadosPk)) {
			return false;
		}
		
		final CitaEstadosPk _cast = (CitaEstadosPk) _other;
		if (idEstadoCita != _cast.idEstadoCita) {
			return false;
		}
		
		if (idEstadoCitaNull != _cast.idEstadoCitaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idEstadoCita ^ (idEstadoCita >>> 32));
		_hashCode = 29 * _hashCode + (idEstadoCitaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.CitaEstadosPk: " );
		ret.append( "idEstadoCita=" + idEstadoCita );
		return ret.toString();
	}

}
