/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Citas implements Serializable
{
	/** 
	 * This attribute maps to the column ID_CITA in the CITAS table.
	 */
	protected long idCita;

	/** 
	 * This attribute maps to the column FECHA_HORA in the CITAS table.
	 */
	protected Date fechaHora;

	/** 
	 * This attribute maps to the column ID_NOTARIA in the CITAS table.
	 */
	protected long idNotaria;

	/** 
	 * This attribute maps to the column ID_ESTADO_CITA in the CITAS table.
	 */
	protected long idEstadoCita;

	/**
	 * Method 'Citas'
	 * 
	 */
	public Citas()
	{
	}

	/**
	 * Method 'getIdCita'
	 * 
	 * @return long
	 */
	public long getIdCita()
	{
		return idCita;
	}

	/**
	 * Method 'setIdCita'
	 * 
	 * @param idCita
	 */
	public void setIdCita(long idCita)
	{
		this.idCita = idCita;
	}

	/**
	 * Method 'getFechaHora'
	 * 
	 * @return Date
	 */
	public Date getFechaHora()
	{
		return fechaHora;
	}

	/**
	 * Method 'setFechaHora'
	 * 
	 * @param fechaHora
	 */
	public void setFechaHora(Date fechaHora)
	{
		this.fechaHora = fechaHora;
	}

	/**
	 * Method 'getIdNotaria'
	 * 
	 * @return long
	 */
	public long getIdNotaria()
	{
		return idNotaria;
	}

	/**
	 * Method 'setIdNotaria'
	 * 
	 * @param idNotaria
	 */
	public void setIdNotaria(long idNotaria)
	{
		this.idNotaria = idNotaria;
	}

	/**
	 * Method 'getIdEstadoCita'
	 * 
	 * @return long
	 */
	public long getIdEstadoCita()
	{
		return idEstadoCita;
	}

	/**
	 * Method 'setIdEstadoCita'
	 * 
	 * @param idEstadoCita
	 */
	public void setIdEstadoCita(long idEstadoCita)
	{
		this.idEstadoCita = idEstadoCita;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Citas)) {
			return false;
		}
		
		final Citas _cast = (Citas) _other;
		if (idCita != _cast.idCita) {
			return false;
		}
		
		if (fechaHora == null ? _cast.fechaHora != fechaHora : !fechaHora.equals( _cast.fechaHora )) {
			return false;
		}
		
		if (idNotaria != _cast.idNotaria) {
			return false;
		}
		
		if (idEstadoCita != _cast.idEstadoCita) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idCita ^ (idCita >>> 32));
		if (fechaHora != null) {
			_hashCode = 29 * _hashCode + fechaHora.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (idNotaria ^ (idNotaria >>> 32));
		_hashCode = 29 * _hashCode + (int) (idEstadoCita ^ (idEstadoCita >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CitasPk
	 */
	public CitasPk createPk()
	{
		return new CitasPk(idCita);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.Citas: " );
		ret.append( "idCita=" + idCita );
		ret.append( ", fechaHora=" + fechaHora );
		ret.append( ", idNotaria=" + idNotaria );
		ret.append( ", idEstadoCita=" + idEstadoCita );
		return ret.toString();
	}

}
