/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CitaEstados implements Serializable
{
	/** 
	 * This attribute maps to the column ID_ESTADO_CITA in the CITA_ESTADOS table.
	 */
	protected long idEstadoCita;

	/** 
	 * This attribute maps to the column NOMBRE in the CITA_ESTADOS table.
	 */
	protected String nombre;

	/**
	 * Method 'CitaEstados'
	 * 
	 */
	public CitaEstados()
	{
	}

	/**
	 * Method 'getIdEstadoCita'
	 * 
	 * @return long
	 */
	public long getIdEstadoCita()
	{
		return idEstadoCita;
	}

	/**
	 * Method 'setIdEstadoCita'
	 * 
	 * @param idEstadoCita
	 */
	public void setIdEstadoCita(long idEstadoCita)
	{
		this.idEstadoCita = idEstadoCita;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CitaEstados)) {
			return false;
		}
		
		final CitaEstados _cast = (CitaEstados) _other;
		if (idEstadoCita != _cast.idEstadoCita) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idEstadoCita ^ (idEstadoCita >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CitaEstadosPk
	 */
	public CitaEstadosPk createPk()
	{
		return new CitaEstadosPk(idEstadoCita);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.CitaEstados: " );
		ret.append( "idEstadoCita=" + idEstadoCita );
		ret.append( ", nombre=" + nombre );
		return ret.toString();
	}

}
