/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the COMUNA table.
 */
public class ComunaPk implements Serializable
{
	protected long idComuna;

	/** 
	 * This attribute represents whether the primitive attribute idComuna is null.
	 */
	protected boolean idComunaNull;

	/** 
	 * Sets the value of idComuna
	 */
	public void setIdComuna(long idComuna)
	{
		this.idComuna = idComuna;
	}

	/** 
	 * Gets the value of idComuna
	 */
	public long getIdComuna()
	{
		return idComuna;
	}

	/**
	 * Method 'ComunaPk'
	 * 
	 */
	public ComunaPk()
	{
	}

	/**
	 * Method 'ComunaPk'
	 * 
	 * @param idComuna
	 */
	public ComunaPk(final long idComuna)
	{
		this.idComuna = idComuna;
	}

	/** 
	 * Sets the value of idComunaNull
	 */
	public void setIdComunaNull(boolean idComunaNull)
	{
		this.idComunaNull = idComunaNull;
	}

	/** 
	 * Gets the value of idComunaNull
	 */
	public boolean isIdComunaNull()
	{
		return idComunaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ComunaPk)) {
			return false;
		}
		
		final ComunaPk _cast = (ComunaPk) _other;
		if (idComuna != _cast.idComuna) {
			return false;
		}
		
		if (idComunaNull != _cast.idComunaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idComuna ^ (idComuna >>> 32));
		_hashCode = 29 * _hashCode + (idComunaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.ComunaPk: " );
		ret.append( "idComuna=" + idComuna );
		return ret.toString();
	}

}
