/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Comuna implements Serializable
{
	/** 
	 * This attribute maps to the column ID_COMUNA in the COMUNA table.
	 */
	protected long idComuna;

	/** 
	 * This attribute maps to the column NOMBRE in the COMUNA table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column ID_PROVINCIA in the COMUNA table.
	 */
	protected long idProvincia;

	/**
	 * Method 'Comuna'
	 * 
	 */
	public Comuna()
	{
	}

	/**
	 * Method 'getIdComuna'
	 * 
	 * @return long
	 */
	public long getIdComuna()
	{
		return idComuna;
	}

	/**
	 * Method 'setIdComuna'
	 * 
	 * @param idComuna
	 */
	public void setIdComuna(long idComuna)
	{
		this.idComuna = idComuna;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getIdProvincia'
	 * 
	 * @return long
	 */
	public long getIdProvincia()
	{
		return idProvincia;
	}

	/**
	 * Method 'setIdProvincia'
	 * 
	 * @param idProvincia
	 */
	public void setIdProvincia(long idProvincia)
	{
		this.idProvincia = idProvincia;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Comuna)) {
			return false;
		}
		
		final Comuna _cast = (Comuna) _other;
		if (idComuna != _cast.idComuna) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (idProvincia != _cast.idProvincia) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idComuna ^ (idComuna >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (idProvincia ^ (idProvincia >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ComunaPk
	 */
	public ComunaPk createPk()
	{
		return new ComunaPk(idComuna);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.Comuna: " );
		ret.append( "idComuna=" + idComuna );
		ret.append( ", nombre=" + nombre );
		ret.append( ", idProvincia=" + idProvincia );
		return ret.toString();
	}

}
