/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class ContratosClientes implements Serializable
{
	/** 
	 * This attribute maps to the column ID_CONTRATO in the CONTRATOS_CLIENTES table.
	 */
	protected long idContrato;

	/** 
	 * This attribute maps to the column ID_USUARIO in the CONTRATOS_CLIENTES table.
	 */
	protected long idUsuario;

	/** 
	 * This attribute maps to the column ID_EMPRESA in the CONTRATOS_CLIENTES table.
	 */
	protected long idEmpresa;

	/** 
	 * This attribute maps to the column CREADO in the CONTRATOS_CLIENTES table.
	 */
	protected Date creado;

	/** 
	 * This attribute maps to the column MODIFICADO in the CONTRATOS_CLIENTES table.
	 */
	protected Date modificado;

	/**
	 * Method 'ContratosClientes'
	 * 
	 */
	public ContratosClientes()
	{
	}

	/**
	 * Method 'getIdContrato'
	 * 
	 * @return long
	 */
	public long getIdContrato()
	{
		return idContrato;
	}

	/**
	 * Method 'setIdContrato'
	 * 
	 * @param idContrato
	 */
	public void setIdContrato(long idContrato)
	{
		this.idContrato = idContrato;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return long
	 */
	public long getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(long idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'getIdEmpresa'
	 * 
	 * @return long
	 */
	public long getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'setIdEmpresa'
	 * 
	 * @param idEmpresa
	 */
	public void setIdEmpresa(long idEmpresa)
	{
		this.idEmpresa = idEmpresa;
	}

	/**
	 * Method 'getCreado'
	 * 
	 * @return Date
	 */
	public Date getCreado()
	{
		return creado;
	}

	/**
	 * Method 'setCreado'
	 * 
	 * @param creado
	 */
	public void setCreado(Date creado)
	{
		this.creado = creado;
	}

	/**
	 * Method 'getModificado'
	 * 
	 * @return Date
	 */
	public Date getModificado()
	{
		return modificado;
	}

	/**
	 * Method 'setModificado'
	 * 
	 * @param modificado
	 */
	public void setModificado(Date modificado)
	{
		this.modificado = modificado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ContratosClientes)) {
			return false;
		}
		
		final ContratosClientes _cast = (ContratosClientes) _other;
		if (idContrato != _cast.idContrato) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (creado == null ? _cast.creado != creado : !creado.equals( _cast.creado )) {
			return false;
		}
		
		if (modificado == null ? _cast.modificado != modificado : !modificado.equals( _cast.modificado )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idContrato ^ (idContrato >>> 32));
		_hashCode = 29 * _hashCode + (int) (idUsuario ^ (idUsuario >>> 32));
		_hashCode = 29 * _hashCode + (int) (idEmpresa ^ (idEmpresa >>> 32));
		if (creado != null) {
			_hashCode = 29 * _hashCode + creado.hashCode();
		}
		
		if (modificado != null) {
			_hashCode = 29 * _hashCode + modificado.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ContratosClientesPk
	 */
	public ContratosClientesPk createPk()
	{
		return new ContratosClientesPk(idContrato, idUsuario, idEmpresa);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.ContratosClientes: " );
		ret.append( "idContrato=" + idContrato );
		ret.append( ", idUsuario=" + idUsuario );
		ret.append( ", idEmpresa=" + idEmpresa );
		ret.append( ", creado=" + creado );
		ret.append( ", modificado=" + modificado );
		return ret.toString();
	}

}
