/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CONTRATOS table.
 */
public class ContratosPk implements Serializable
{
	protected long idContrato;

	/** 
	 * This attribute represents whether the primitive attribute idContrato is null.
	 */
	protected boolean idContratoNull;

	/** 
	 * Sets the value of idContrato
	 */
	public void setIdContrato(long idContrato)
	{
		this.idContrato = idContrato;
	}

	/** 
	 * Gets the value of idContrato
	 */
	public long getIdContrato()
	{
		return idContrato;
	}

	/**
	 * Method 'ContratosPk'
	 * 
	 */
	public ContratosPk()
	{
	}

	/**
	 * Method 'ContratosPk'
	 * 
	 * @param idContrato
	 */
	public ContratosPk(final long idContrato)
	{
		this.idContrato = idContrato;
	}

	/** 
	 * Sets the value of idContratoNull
	 */
	public void setIdContratoNull(boolean idContratoNull)
	{
		this.idContratoNull = idContratoNull;
	}

	/** 
	 * Gets the value of idContratoNull
	 */
	public boolean isIdContratoNull()
	{
		return idContratoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ContratosPk)) {
			return false;
		}
		
		final ContratosPk _cast = (ContratosPk) _other;
		if (idContrato != _cast.idContrato) {
			return false;
		}
		
		if (idContratoNull != _cast.idContratoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idContrato ^ (idContrato >>> 32));
		_hashCode = 29 * _hashCode + (idContratoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.ContratosPk: " );
		ret.append( "idContrato=" + idContrato );
		return ret.toString();
	}

}
