/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CONTRATOS_CLIENTES table.
 */
public class ContratosClientesPk implements Serializable
{
	protected long idContrato;

	protected long idUsuario;

	protected long idEmpresa;

	/** 
	 * This attribute represents whether the primitive attribute idContrato is null.
	 */
	protected boolean idContratoNull;

	/** 
	 * This attribute represents whether the primitive attribute idUsuario is null.
	 */
	protected boolean idUsuarioNull;

	/** 
	 * This attribute represents whether the primitive attribute idEmpresa is null.
	 */
	protected boolean idEmpresaNull;

	/** 
	 * Sets the value of idContrato
	 */
	public void setIdContrato(long idContrato)
	{
		this.idContrato = idContrato;
	}

	/** 
	 * Gets the value of idContrato
	 */
	public long getIdContrato()
	{
		return idContrato;
	}

	/** 
	 * Sets the value of idUsuario
	 */
	public void setIdUsuario(long idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/** 
	 * Gets the value of idUsuario
	 */
	public long getIdUsuario()
	{
		return idUsuario;
	}

	/** 
	 * Sets the value of idEmpresa
	 */
	public void setIdEmpresa(long idEmpresa)
	{
		this.idEmpresa = idEmpresa;
	}

	/** 
	 * Gets the value of idEmpresa
	 */
	public long getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'ContratosClientesPk'
	 * 
	 */
	public ContratosClientesPk()
	{
	}

	/**
	 * Method 'ContratosClientesPk'
	 * 
	 * @param idContrato
	 * @param idUsuario
	 * @param idEmpresa
	 */
	public ContratosClientesPk(final long idContrato, final long idUsuario, final long idEmpresa)
	{
		this.idContrato = idContrato;
		this.idUsuario = idUsuario;
		this.idEmpresa = idEmpresa;
	}

	/** 
	 * Sets the value of idContratoNull
	 */
	public void setIdContratoNull(boolean idContratoNull)
	{
		this.idContratoNull = idContratoNull;
	}

	/** 
	 * Gets the value of idContratoNull
	 */
	public boolean isIdContratoNull()
	{
		return idContratoNull;
	}

	/** 
	 * Sets the value of idUsuarioNull
	 */
	public void setIdUsuarioNull(boolean idUsuarioNull)
	{
		this.idUsuarioNull = idUsuarioNull;
	}

	/** 
	 * Gets the value of idUsuarioNull
	 */
	public boolean isIdUsuarioNull()
	{
		return idUsuarioNull;
	}

	/** 
	 * Sets the value of idEmpresaNull
	 */
	public void setIdEmpresaNull(boolean idEmpresaNull)
	{
		this.idEmpresaNull = idEmpresaNull;
	}

	/** 
	 * Gets the value of idEmpresaNull
	 */
	public boolean isIdEmpresaNull()
	{
		return idEmpresaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ContratosClientesPk)) {
			return false;
		}
		
		final ContratosClientesPk _cast = (ContratosClientesPk) _other;
		if (idContrato != _cast.idContrato) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idContratoNull != _cast.idContratoNull) {
			return false;
		}
		
		if (idUsuarioNull != _cast.idUsuarioNull) {
			return false;
		}
		
		if (idEmpresaNull != _cast.idEmpresaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idContrato ^ (idContrato >>> 32));
		_hashCode = 29 * _hashCode + (int) (idUsuario ^ (idUsuario >>> 32));
		_hashCode = 29 * _hashCode + (int) (idEmpresa ^ (idEmpresa >>> 32));
		_hashCode = 29 * _hashCode + (idContratoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idUsuarioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idEmpresaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.ContratosClientesPk: " );
		ret.append( "idContrato=" + idContrato );
		ret.append( ", idUsuario=" + idUsuario );
		ret.append( ", idEmpresa=" + idEmpresa );
		return ret.toString();
	}

}
