/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ContratoDetalles implements Serializable
{
	/** 
	 * This attribute maps to the column ID_DETALLE_CONTRATO in the CONTRATO_DETALLES table.
	 */
	protected long idDetalleContrato;

	/** 
	 * This attribute maps to the column SERVICIO in the CONTRATO_DETALLES table.
	 */
	protected String servicio;

	/** 
	 * This attribute maps to the column MONTO in the CONTRATO_DETALLES table.
	 */
	protected long monto;

	/**
	 * Method 'ContratoDetalles'
	 * 
	 */
	public ContratoDetalles()
	{
	}

	/**
	 * Method 'getIdDetalleContrato'
	 * 
	 * @return long
	 */
	public long getIdDetalleContrato()
	{
		return idDetalleContrato;
	}

	/**
	 * Method 'setIdDetalleContrato'
	 * 
	 * @param idDetalleContrato
	 */
	public void setIdDetalleContrato(long idDetalleContrato)
	{
		this.idDetalleContrato = idDetalleContrato;
	}

	/**
	 * Method 'getServicio'
	 * 
	 * @return String
	 */
	public String getServicio()
	{
		return servicio;
	}

	/**
	 * Method 'setServicio'
	 * 
	 * @param servicio
	 */
	public void setServicio(String servicio)
	{
		this.servicio = servicio;
	}

	/**
	 * Method 'getMonto'
	 * 
	 * @return long
	 */
	public long getMonto()
	{
		return monto;
	}

	/**
	 * Method 'setMonto'
	 * 
	 * @param monto
	 */
	public void setMonto(long monto)
	{
		this.monto = monto;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ContratoDetalles)) {
			return false;
		}
		
		final ContratoDetalles _cast = (ContratoDetalles) _other;
		if (idDetalleContrato != _cast.idDetalleContrato) {
			return false;
		}
		
		if (servicio == null ? _cast.servicio != servicio : !servicio.equals( _cast.servicio )) {
			return false;
		}
		
		if (monto != _cast.monto) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idDetalleContrato ^ (idDetalleContrato >>> 32));
		if (servicio != null) {
			_hashCode = 29 * _hashCode + servicio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (monto ^ (monto >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ContratoDetallesPk
	 */
	public ContratoDetallesPk createPk()
	{
		return new ContratoDetallesPk(idDetalleContrato);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.ContratoDetalles: " );
		ret.append( "idDetalleContrato=" + idDetalleContrato );
		ret.append( ", servicio=" + servicio );
		ret.append( ", monto=" + monto );
		return ret.toString();
	}

}
