/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DeleteCitasParam implements Serializable
{
	protected long vIdCita;

	/** 
	 * This attribute represents whether the primitive attribute vIdCita is null.
	 */
	protected boolean vIdCitaNull = true;

	protected int vSalida;

	/** 
	 * This attribute represents whether the primitive attribute vSalida is null.
	 */
	protected boolean vSalidaNull = true;

	/**
	 * Method 'DeleteCitasParam'
	 * 
	 */
	public DeleteCitasParam()
	{
	}

	/**
	 * Method 'getVIdCita'
	 * 
	 * @return long
	 */
	public long getVIdCita()
	{
		return vIdCita;
	}

	/**
	 * Method 'setVIdCita'
	 * 
	 * @param vIdCita
	 */
	public void setVIdCita(long vIdCita)
	{
		this.vIdCita = vIdCita;
	}

	/** 
	 * Sets the value of vIdCitaNull
	 */
	public void setVIdCitaNull(boolean vIdCitaNull)
	{
		this.vIdCitaNull = vIdCitaNull;
	}

	/** 
	 * Gets the value of vIdCitaNull
	 */
	public boolean isVIdCitaNull()
	{
		return vIdCitaNull;
	}

	/**
	 * Method 'getVSalida'
	 * 
	 * @return int
	 */
	public int getVSalida()
	{
		return vSalida;
	}

	/**
	 * Method 'setVSalida'
	 * 
	 * @param vSalida
	 */
	public void setVSalida(int vSalida)
	{
		this.vSalida = vSalida;
	}

	/** 
	 * Sets the value of vSalidaNull
	 */
	public void setVSalidaNull(boolean vSalidaNull)
	{
		this.vSalidaNull = vSalidaNull;
	}

	/** 
	 * Gets the value of vSalidaNull
	 */
	public boolean isVSalidaNull()
	{
		return vSalidaNull;
	}

}
