/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DeleteContratoParam implements Serializable
{
	protected long vId;

	/** 
	 * This attribute represents whether the primitive attribute vId is null.
	 */
	protected boolean vIdNull = true;

	protected int vSalida;

	/** 
	 * This attribute represents whether the primitive attribute vSalida is null.
	 */
	protected boolean vSalidaNull = true;

	/**
	 * Method 'DeleteContratoParam'
	 * 
	 */
	public DeleteContratoParam()
	{
	}

	/**
	 * Method 'getVId'
	 * 
	 * @return long
	 */
	public long getVId()
	{
		return vId;
	}

	/**
	 * Method 'setVId'
	 * 
	 * @param vId
	 */
	public void setVId(long vId)
	{
		this.vId = vId;
	}

	/** 
	 * Sets the value of vIdNull
	 */
	public void setVIdNull(boolean vIdNull)
	{
		this.vIdNull = vIdNull;
	}

	/** 
	 * Gets the value of vIdNull
	 */
	public boolean isVIdNull()
	{
		return vIdNull;
	}

	/**
	 * Method 'getVSalida'
	 * 
	 * @return int
	 */
	public int getVSalida()
	{
		return vSalida;
	}

	/**
	 * Method 'setVSalida'
	 * 
	 * @param vSalida
	 */
	public void setVSalida(int vSalida)
	{
		this.vSalida = vSalida;
	}

	/** 
	 * Sets the value of vSalidaNull
	 */
	public void setVSalidaNull(boolean vSalidaNull)
	{
		this.vSalidaNull = vSalidaNull;
	}

	/** 
	 * Gets the value of vSalidaNull
	 */
	public boolean isVSalidaNull()
	{
		return vSalidaNull;
	}

}
