/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the DILIGENCIAS table.
 */
public class DiligenciasPk implements Serializable
{
	protected long idDiligencia;

	/** 
	 * This attribute represents whether the primitive attribute idDiligencia is null.
	 */
	protected boolean idDiligenciaNull;

	/** 
	 * Sets the value of idDiligencia
	 */
	public void setIdDiligencia(long idDiligencia)
	{
		this.idDiligencia = idDiligencia;
	}

	/** 
	 * Gets the value of idDiligencia
	 */
	public long getIdDiligencia()
	{
		return idDiligencia;
	}

	/**
	 * Method 'DiligenciasPk'
	 * 
	 */
	public DiligenciasPk()
	{
	}

	/**
	 * Method 'DiligenciasPk'
	 * 
	 * @param idDiligencia
	 */
	public DiligenciasPk(final long idDiligencia)
	{
		this.idDiligencia = idDiligencia;
	}

	/** 
	 * Sets the value of idDiligenciaNull
	 */
	public void setIdDiligenciaNull(boolean idDiligenciaNull)
	{
		this.idDiligenciaNull = idDiligenciaNull;
	}

	/** 
	 * Gets the value of idDiligenciaNull
	 */
	public boolean isIdDiligenciaNull()
	{
		return idDiligenciaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DiligenciasPk)) {
			return false;
		}
		
		final DiligenciasPk _cast = (DiligenciasPk) _other;
		if (idDiligencia != _cast.idDiligencia) {
			return false;
		}
		
		if (idDiligenciaNull != _cast.idDiligenciaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idDiligencia ^ (idDiligencia >>> 32));
		_hashCode = 29 * _hashCode + (idDiligenciaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.DiligenciasPk: " );
		ret.append( "idDiligencia=" + idDiligencia );
		return ret.toString();
	}

}
