/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Diligencias implements Serializable
{
	/** 
	 * This attribute maps to the column ID_DILIGENCIA in the DILIGENCIAS table.
	 */
	protected long idDiligencia;

	/** 
	 * This attribute maps to the column FECHA_HORA in the DILIGENCIAS table.
	 */
	protected Date fechaHora;

	/** 
	 * This attribute maps to the column DESCRIPCION in the DILIGENCIAS table.
	 */
	protected String descripcion;

	/** 
	 * This attribute maps to the column ID_CAUSA in the DILIGENCIAS table.
	 */
	protected long idCausa;

	/** 
	 * This attribute represents whether the primitive attribute idCausa is null.
	 */
	protected boolean idCausaNull = true;

	/**
	 * Method 'Diligencias'
	 * 
	 */
	public Diligencias()
	{
	}

	/**
	 * Method 'getIdDiligencia'
	 * 
	 * @return long
	 */
	public long getIdDiligencia()
	{
		return idDiligencia;
	}

	/**
	 * Method 'setIdDiligencia'
	 * 
	 * @param idDiligencia
	 */
	public void setIdDiligencia(long idDiligencia)
	{
		this.idDiligencia = idDiligencia;
	}

	/**
	 * Method 'getFechaHora'
	 * 
	 * @return Date
	 */
	public Date getFechaHora()
	{
		return fechaHora;
	}

	/**
	 * Method 'setFechaHora'
	 * 
	 * @param fechaHora
	 */
	public void setFechaHora(Date fechaHora)
	{
		this.fechaHora = fechaHora;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	/**
	 * Method 'getIdCausa'
	 * 
	 * @return long
	 */
	public long getIdCausa()
	{
		return idCausa;
	}

	/**
	 * Method 'setIdCausa'
	 * 
	 * @param idCausa
	 */
	public void setIdCausa(long idCausa)
	{
		this.idCausa = idCausa;
		this.idCausaNull = false;
	}

	/**
	 * Method 'setIdCausaNull'
	 * 
	 * @param value
	 */
	public void setIdCausaNull(boolean value)
	{
		this.idCausaNull = value;
	}

	/**
	 * Method 'isIdCausaNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdCausaNull()
	{
		return idCausaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Diligencias)) {
			return false;
		}
		
		final Diligencias _cast = (Diligencias) _other;
		if (idDiligencia != _cast.idDiligencia) {
			return false;
		}
		
		if (fechaHora == null ? _cast.fechaHora != fechaHora : !fechaHora.equals( _cast.fechaHora )) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (idCausa != _cast.idCausa) {
			return false;
		}
		
		if (idCausaNull != _cast.idCausaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idDiligencia ^ (idDiligencia >>> 32));
		if (fechaHora != null) {
			_hashCode = 29 * _hashCode + fechaHora.hashCode();
		}
		
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (idCausa ^ (idCausa >>> 32));
		_hashCode = 29 * _hashCode + (idCausaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DiligenciasPk
	 */
	public DiligenciasPk createPk()
	{
		return new DiligenciasPk(idDiligencia);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.Diligencias: " );
		ret.append( "idDiligencia=" + idDiligencia );
		ret.append( ", fechaHora=" + fechaHora );
		ret.append( ", descripcion=" + descripcion );
		ret.append( ", idCausa=" + idCausa );
		return ret.toString();
	}

}
