/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DocEstados implements Serializable
{
	/** 
	 * This attribute maps to the column ID_ESTADO_DOC in the DOC_ESTADOS table.
	 */
	protected long idEstadoDoc;

	/** 
	 * This attribute maps to the column NOMBRE in the DOC_ESTADOS table.
	 */
	protected String nombre;

	/**
	 * Method 'DocEstados'
	 * 
	 */
	public DocEstados()
	{
	}

	/**
	 * Method 'getIdEstadoDoc'
	 * 
	 * @return long
	 */
	public long getIdEstadoDoc()
	{
		return idEstadoDoc;
	}

	/**
	 * Method 'setIdEstadoDoc'
	 * 
	 * @param idEstadoDoc
	 */
	public void setIdEstadoDoc(long idEstadoDoc)
	{
		this.idEstadoDoc = idEstadoDoc;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DocEstados)) {
			return false;
		}
		
		final DocEstados _cast = (DocEstados) _other;
		if (idEstadoDoc != _cast.idEstadoDoc) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idEstadoDoc ^ (idEstadoDoc >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DocEstadosPk
	 */
	public DocEstadosPk createPk()
	{
		return new DocEstadosPk(idEstadoDoc);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.DocEstados: " );
		ret.append( "idEstadoDoc=" + idEstadoDoc );
		ret.append( ", nombre=" + nombre );
		return ret.toString();
	}

}
