/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the DOCUMENTOS_CITAS table.
 */
public class DocumentosCitasPk implements Serializable
{
	protected long idCita;

	/** 
	 * This attribute represents whether the primitive attribute idCita is null.
	 */
	protected boolean idCitaNull;

	/** 
	 * Sets the value of idCita
	 */
	public void setIdCita(long idCita)
	{
		this.idCita = idCita;
	}

	/** 
	 * Gets the value of idCita
	 */
	public long getIdCita()
	{
		return idCita;
	}

	/**
	 * Method 'DocumentosCitasPk'
	 * 
	 */
	public DocumentosCitasPk()
	{
	}

	/**
	 * Method 'DocumentosCitasPk'
	 * 
	 * @param idCita
	 */
	public DocumentosCitasPk(final long idCita)
	{
		this.idCita = idCita;
	}

	/** 
	 * Sets the value of idCitaNull
	 */
	public void setIdCitaNull(boolean idCitaNull)
	{
		this.idCitaNull = idCitaNull;
	}

	/** 
	 * Gets the value of idCitaNull
	 */
	public boolean isIdCitaNull()
	{
		return idCitaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DocumentosCitasPk)) {
			return false;
		}
		
		final DocumentosCitasPk _cast = (DocumentosCitasPk) _other;
		if (idCita != _cast.idCita) {
			return false;
		}
		
		if (idCitaNull != _cast.idCitaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idCita ^ (idCita >>> 32));
		_hashCode = 29 * _hashCode + (idCitaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.DocumentosCitasPk: " );
		ret.append( "idCita=" + idCita );
		return ret.toString();
	}

}
