/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class DocumentosCitas implements Serializable
{
	/** 
	 * This attribute maps to the column ID_CITA in the DOCUMENTOS_CITAS table.
	 */
	protected long idCita;

	/** 
	 * This attribute maps to the column ID_DOCUMENTO in the DOCUMENTOS_CITAS table.
	 */
	protected long idDocumento;

	/** 
	 * This attribute maps to the column ID_ESTADO_DOC in the DOCUMENTOS_CITAS table.
	 */
	protected long idEstadoDoc;

	/** 
	 * This attribute maps to the column CREADO in the DOCUMENTOS_CITAS table.
	 */
	protected Date creado;

	/**
	 * Method 'DocumentosCitas'
	 * 
	 */
	public DocumentosCitas()
	{
	}

	/**
	 * Method 'getIdCita'
	 * 
	 * @return long
	 */
	public long getIdCita()
	{
		return idCita;
	}

	/**
	 * Method 'setIdCita'
	 * 
	 * @param idCita
	 */
	public void setIdCita(long idCita)
	{
		this.idCita = idCita;
	}

	/**
	 * Method 'getIdDocumento'
	 * 
	 * @return long
	 */
	public long getIdDocumento()
	{
		return idDocumento;
	}

	/**
	 * Method 'setIdDocumento'
	 * 
	 * @param idDocumento
	 */
	public void setIdDocumento(long idDocumento)
	{
		this.idDocumento = idDocumento;
	}

	/**
	 * Method 'getIdEstadoDoc'
	 * 
	 * @return long
	 */
	public long getIdEstadoDoc()
	{
		return idEstadoDoc;
	}

	/**
	 * Method 'setIdEstadoDoc'
	 * 
	 * @param idEstadoDoc
	 */
	public void setIdEstadoDoc(long idEstadoDoc)
	{
		this.idEstadoDoc = idEstadoDoc;
	}

	/**
	 * Method 'getCreado'
	 * 
	 * @return Date
	 */
	public Date getCreado()
	{
		return creado;
	}

	/**
	 * Method 'setCreado'
	 * 
	 * @param creado
	 */
	public void setCreado(Date creado)
	{
		this.creado = creado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DocumentosCitas)) {
			return false;
		}
		
		final DocumentosCitas _cast = (DocumentosCitas) _other;
		if (idCita != _cast.idCita) {
			return false;
		}
		
		if (idDocumento != _cast.idDocumento) {
			return false;
		}
		
		if (idEstadoDoc != _cast.idEstadoDoc) {
			return false;
		}
		
		if (creado == null ? _cast.creado != creado : !creado.equals( _cast.creado )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idCita ^ (idCita >>> 32));
		_hashCode = 29 * _hashCode + (int) (idDocumento ^ (idDocumento >>> 32));
		_hashCode = 29 * _hashCode + (int) (idEstadoDoc ^ (idEstadoDoc >>> 32));
		if (creado != null) {
			_hashCode = 29 * _hashCode + creado.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DocumentosCitasPk
	 */
	public DocumentosCitasPk createPk()
	{
		return new DocumentosCitasPk(idCita);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.DocumentosCitas: " );
		ret.append( "idCita=" + idCita );
		ret.append( ", idDocumento=" + idDocumento );
		ret.append( ", idEstadoDoc=" + idEstadoDoc );
		ret.append( ", creado=" + creado );
		return ret.toString();
	}

}
