/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EmpresaClientes implements Serializable
{
	/** 
	 * This attribute maps to the column ID_EMPRESA in the EMPRESA_CLIENTES table.
	 */
	protected long idEmpresa;

	/** 
	 * This attribute maps to the column ID_USUARIO in the EMPRESA_CLIENTES table.
	 */
	protected long idUsuario;

	/**
	 * Method 'EmpresaClientes'
	 * 
	 */
	public EmpresaClientes()
	{
	}

	/**
	 * Method 'getIdEmpresa'
	 * 
	 * @return long
	 */
	public long getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'setIdEmpresa'
	 * 
	 * @param idEmpresa
	 */
	public void setIdEmpresa(long idEmpresa)
	{
		this.idEmpresa = idEmpresa;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return long
	 */
	public long getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(long idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmpresaClientes)) {
			return false;
		}
		
		final EmpresaClientes _cast = (EmpresaClientes) _other;
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idEmpresa ^ (idEmpresa >>> 32));
		_hashCode = 29 * _hashCode + (int) (idUsuario ^ (idUsuario >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmpresaClientesPk
	 */
	public EmpresaClientesPk createPk()
	{
		return new EmpresaClientesPk(idEmpresa, idUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.EmpresaClientes: " );
		ret.append( "idEmpresa=" + idEmpresa );
		ret.append( ", idUsuario=" + idUsuario );
		return ret.toString();
	}

}
