/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the EMPRESA_CLIENTES table.
 */
public class EmpresaClientesPk implements Serializable
{
	protected long idEmpresa;

	protected long idUsuario;

	/** 
	 * This attribute represents whether the primitive attribute idEmpresa is null.
	 */
	protected boolean idEmpresaNull;

	/** 
	 * This attribute represents whether the primitive attribute idUsuario is null.
	 */
	protected boolean idUsuarioNull;

	/** 
	 * Sets the value of idEmpresa
	 */
	public void setIdEmpresa(long idEmpresa)
	{
		this.idEmpresa = idEmpresa;
	}

	/** 
	 * Gets the value of idEmpresa
	 */
	public long getIdEmpresa()
	{
		return idEmpresa;
	}

	/** 
	 * Sets the value of idUsuario
	 */
	public void setIdUsuario(long idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/** 
	 * Gets the value of idUsuario
	 */
	public long getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'EmpresaClientesPk'
	 * 
	 */
	public EmpresaClientesPk()
	{
	}

	/**
	 * Method 'EmpresaClientesPk'
	 * 
	 * @param idEmpresa
	 * @param idUsuario
	 */
	public EmpresaClientesPk(final long idEmpresa, final long idUsuario)
	{
		this.idEmpresa = idEmpresa;
		this.idUsuario = idUsuario;
	}

	/** 
	 * Sets the value of idEmpresaNull
	 */
	public void setIdEmpresaNull(boolean idEmpresaNull)
	{
		this.idEmpresaNull = idEmpresaNull;
	}

	/** 
	 * Gets the value of idEmpresaNull
	 */
	public boolean isIdEmpresaNull()
	{
		return idEmpresaNull;
	}

	/** 
	 * Sets the value of idUsuarioNull
	 */
	public void setIdUsuarioNull(boolean idUsuarioNull)
	{
		this.idUsuarioNull = idUsuarioNull;
	}

	/** 
	 * Gets the value of idUsuarioNull
	 */
	public boolean isIdUsuarioNull()
	{
		return idUsuarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmpresaClientesPk)) {
			return false;
		}
		
		final EmpresaClientesPk _cast = (EmpresaClientesPk) _other;
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idEmpresaNull != _cast.idEmpresaNull) {
			return false;
		}
		
		if (idUsuarioNull != _cast.idUsuarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idEmpresa ^ (idEmpresa >>> 32));
		_hashCode = 29 * _hashCode + (int) (idUsuario ^ (idUsuario >>> 32));
		_hashCode = 29 * _hashCode + (idEmpresaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idUsuarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.EmpresaClientesPk: " );
		ret.append( "idEmpresa=" + idEmpresa );
		ret.append( ", idUsuario=" + idUsuario );
		return ret.toString();
	}

}
