/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class FormaPago implements Serializable
{
	/** 
	 * This attribute maps to the column ID_FORMA_PAGO in the FORMA_PAGO table.
	 */
	protected long idFormaPago;

	/** 
	 * This attribute maps to the column NOMBRE in the FORMA_PAGO table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column CANTIDAD_CUOTAS in the FORMA_PAGO table.
	 */
	protected int cantidadCuotas;

	/**
	 * Method 'FormaPago'
	 * 
	 */
	public FormaPago()
	{
	}

	/**
	 * Method 'getIdFormaPago'
	 * 
	 * @return long
	 */
	public long getIdFormaPago()
	{
		return idFormaPago;
	}

	/**
	 * Method 'setIdFormaPago'
	 * 
	 * @param idFormaPago
	 */
	public void setIdFormaPago(long idFormaPago)
	{
		this.idFormaPago = idFormaPago;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getCantidadCuotas'
	 * 
	 * @return int
	 */
	public int getCantidadCuotas()
	{
		return cantidadCuotas;
	}

	/**
	 * Method 'setCantidadCuotas'
	 * 
	 * @param cantidadCuotas
	 */
	public void setCantidadCuotas(int cantidadCuotas)
	{
		this.cantidadCuotas = cantidadCuotas;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FormaPago)) {
			return false;
		}
		
		final FormaPago _cast = (FormaPago) _other;
		if (idFormaPago != _cast.idFormaPago) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (cantidadCuotas != _cast.cantidadCuotas) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idFormaPago ^ (idFormaPago >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cantidadCuotas;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FormaPagoPk
	 */
	public FormaPagoPk createPk()
	{
		return new FormaPagoPk(idFormaPago);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.FormaPago: " );
		ret.append( "idFormaPago=" + idFormaPago );
		ret.append( ", nombre=" + nombre );
		ret.append( ", cantidadCuotas=" + cantidadCuotas );
		return ret.toString();
	}

}
