/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the NOTARIAS table.
 */
public class NotariasPk implements Serializable
{
	protected long idNotaria;

	/** 
	 * This attribute represents whether the primitive attribute idNotaria is null.
	 */
	protected boolean idNotariaNull;

	/** 
	 * Sets the value of idNotaria
	 */
	public void setIdNotaria(long idNotaria)
	{
		this.idNotaria = idNotaria;
	}

	/** 
	 * Gets the value of idNotaria
	 */
	public long getIdNotaria()
	{
		return idNotaria;
	}

	/**
	 * Method 'NotariasPk'
	 * 
	 */
	public NotariasPk()
	{
	}

	/**
	 * Method 'NotariasPk'
	 * 
	 * @param idNotaria
	 */
	public NotariasPk(final long idNotaria)
	{
		this.idNotaria = idNotaria;
	}

	/** 
	 * Sets the value of idNotariaNull
	 */
	public void setIdNotariaNull(boolean idNotariaNull)
	{
		this.idNotariaNull = idNotariaNull;
	}

	/** 
	 * Gets the value of idNotariaNull
	 */
	public boolean isIdNotariaNull()
	{
		return idNotariaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NotariasPk)) {
			return false;
		}
		
		final NotariasPk _cast = (NotariasPk) _other;
		if (idNotaria != _cast.idNotaria) {
			return false;
		}
		
		if (idNotariaNull != _cast.idNotariaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idNotaria ^ (idNotaria >>> 32));
		_hashCode = 29 * _hashCode + (idNotariaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.NotariasPk: " );
		ret.append( "idNotaria=" + idNotaria );
		return ret.toString();
	}

}
