/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class NotariasUsuarios implements Serializable
{
	/** 
	 * This attribute maps to the column ID_NOTARIA in the NOTARIAS_USUARIOS table.
	 */
	protected long idNotaria;

	/** 
	 * This attribute maps to the column ID_USUARIO in the NOTARIAS_USUARIOS table.
	 */
	protected long idUsuario;

	/**
	 * Method 'NotariasUsuarios'
	 * 
	 */
	public NotariasUsuarios()
	{
	}

	/**
	 * Method 'getIdNotaria'
	 * 
	 * @return long
	 */
	public long getIdNotaria()
	{
		return idNotaria;
	}

	/**
	 * Method 'setIdNotaria'
	 * 
	 * @param idNotaria
	 */
	public void setIdNotaria(long idNotaria)
	{
		this.idNotaria = idNotaria;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return long
	 */
	public long getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(long idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NotariasUsuarios)) {
			return false;
		}
		
		final NotariasUsuarios _cast = (NotariasUsuarios) _other;
		if (idNotaria != _cast.idNotaria) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idNotaria ^ (idNotaria >>> 32));
		_hashCode = 29 * _hashCode + (int) (idUsuario ^ (idUsuario >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NotariasUsuariosPk
	 */
	public NotariasUsuariosPk createPk()
	{
		return new NotariasUsuariosPk(idNotaria, idUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.NotariasUsuarios: " );
		ret.append( "idNotaria=" + idNotaria );
		ret.append( ", idUsuario=" + idUsuario );
		return ret.toString();
	}

}
