/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PAGOS table.
 */
public class PagosPk implements Serializable
{
	protected long idPago;

	/** 
	 * This attribute represents whether the primitive attribute idPago is null.
	 */
	protected boolean idPagoNull;

	/** 
	 * Sets the value of idPago
	 */
	public void setIdPago(long idPago)
	{
		this.idPago = idPago;
	}

	/** 
	 * Gets the value of idPago
	 */
	public long getIdPago()
	{
		return idPago;
	}

	/**
	 * Method 'PagosPk'
	 * 
	 */
	public PagosPk()
	{
	}

	/**
	 * Method 'PagosPk'
	 * 
	 * @param idPago
	 */
	public PagosPk(final long idPago)
	{
		this.idPago = idPago;
	}

	/** 
	 * Sets the value of idPagoNull
	 */
	public void setIdPagoNull(boolean idPagoNull)
	{
		this.idPagoNull = idPagoNull;
	}

	/** 
	 * Gets the value of idPagoNull
	 */
	public boolean isIdPagoNull()
	{
		return idPagoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PagosPk)) {
			return false;
		}
		
		final PagosPk _cast = (PagosPk) _other;
		if (idPago != _cast.idPago) {
			return false;
		}
		
		if (idPagoNull != _cast.idPagoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idPago ^ (idPago >>> 32));
		_hashCode = 29 * _hashCode + (idPagoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.PagosPk: " );
		ret.append( "idPago=" + idPago );
		return ret.toString();
	}

}
