/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Pagos implements Serializable
{
	/** 
	 * This attribute maps to the column ID_PAGO in the PAGOS table.
	 */
	protected long idPago;

	/** 
	 * This attribute maps to the column FECHA_HORA in the PAGOS table.
	 */
	protected Date fechaHora;

	/** 
	 * This attribute maps to the column MONTO in the PAGOS table.
	 */
	protected long monto;

	/** 
	 * This attribute maps to the column CREADO in the PAGOS table.
	 */
	protected Date creado;

	/** 
	 * This attribute maps to the column MODIFICADO in the PAGOS table.
	 */
	protected Date modificado;

	/** 
	 * This attribute maps to the column ID_CONTRATO in the PAGOS table.
	 */
	protected long idContrato;

	/** 
	 * This attribute represents whether the primitive attribute idContrato is null.
	 */
	protected boolean idContratoNull = true;

	/**
	 * Method 'Pagos'
	 * 
	 */
	public Pagos()
	{
	}

	/**
	 * Method 'getIdPago'
	 * 
	 * @return long
	 */
	public long getIdPago()
	{
		return idPago;
	}

	/**
	 * Method 'setIdPago'
	 * 
	 * @param idPago
	 */
	public void setIdPago(long idPago)
	{
		this.idPago = idPago;
	}

	/**
	 * Method 'getFechaHora'
	 * 
	 * @return Date
	 */
	public Date getFechaHora()
	{
		return fechaHora;
	}

	/**
	 * Method 'setFechaHora'
	 * 
	 * @param fechaHora
	 */
	public void setFechaHora(Date fechaHora)
	{
		this.fechaHora = fechaHora;
	}

	/**
	 * Method 'getMonto'
	 * 
	 * @return long
	 */
	public long getMonto()
	{
		return monto;
	}

	/**
	 * Method 'setMonto'
	 * 
	 * @param monto
	 */
	public void setMonto(long monto)
	{
		this.monto = monto;
	}

	/**
	 * Method 'getCreado'
	 * 
	 * @return Date
	 */
	public Date getCreado()
	{
		return creado;
	}

	/**
	 * Method 'setCreado'
	 * 
	 * @param creado
	 */
	public void setCreado(Date creado)
	{
		this.creado = creado;
	}

	/**
	 * Method 'getModificado'
	 * 
	 * @return Date
	 */
	public Date getModificado()
	{
		return modificado;
	}

	/**
	 * Method 'setModificado'
	 * 
	 * @param modificado
	 */
	public void setModificado(Date modificado)
	{
		this.modificado = modificado;
	}

	/**
	 * Method 'getIdContrato'
	 * 
	 * @return long
	 */
	public long getIdContrato()
	{
		return idContrato;
	}

	/**
	 * Method 'setIdContrato'
	 * 
	 * @param idContrato
	 */
	public void setIdContrato(long idContrato)
	{
		this.idContrato = idContrato;
		this.idContratoNull = false;
	}

	/**
	 * Method 'setIdContratoNull'
	 * 
	 * @param value
	 */
	public void setIdContratoNull(boolean value)
	{
		this.idContratoNull = value;
	}

	/**
	 * Method 'isIdContratoNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdContratoNull()
	{
		return idContratoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pagos)) {
			return false;
		}
		
		final Pagos _cast = (Pagos) _other;
		if (idPago != _cast.idPago) {
			return false;
		}
		
		if (fechaHora == null ? _cast.fechaHora != fechaHora : !fechaHora.equals( _cast.fechaHora )) {
			return false;
		}
		
		if (monto != _cast.monto) {
			return false;
		}
		
		if (creado == null ? _cast.creado != creado : !creado.equals( _cast.creado )) {
			return false;
		}
		
		if (modificado == null ? _cast.modificado != modificado : !modificado.equals( _cast.modificado )) {
			return false;
		}
		
		if (idContrato != _cast.idContrato) {
			return false;
		}
		
		if (idContratoNull != _cast.idContratoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idPago ^ (idPago >>> 32));
		if (fechaHora != null) {
			_hashCode = 29 * _hashCode + fechaHora.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (monto ^ (monto >>> 32));
		if (creado != null) {
			_hashCode = 29 * _hashCode + creado.hashCode();
		}
		
		if (modificado != null) {
			_hashCode = 29 * _hashCode + modificado.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (idContrato ^ (idContrato >>> 32));
		_hashCode = 29 * _hashCode + (idContratoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PagosPk
	 */
	public PagosPk createPk()
	{
		return new PagosPk(idPago);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.Pagos: " );
		ret.append( "idPago=" + idPago );
		ret.append( ", fechaHora=" + fechaHora );
		ret.append( ", monto=" + monto );
		ret.append( ", creado=" + creado );
		ret.append( ", modificado=" + modificado );
		ret.append( ", idContrato=" + idContrato );
		return ret.toString();
	}

}
