/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class PlanPago implements Serializable
{
	/** 
	 * This attribute maps to the column ID_PLAN_PAGO in the PLAN_PAGO table.
	 */
	protected long idPlanPago;

	/** 
	 * This attribute maps to the column NOMBRE in the PLAN_PAGO table.
	 */
	protected String nombre;

	/**
	 * Method 'PlanPago'
	 * 
	 */
	public PlanPago()
	{
	}

	/**
	 * Method 'getIdPlanPago'
	 * 
	 * @return long
	 */
	public long getIdPlanPago()
	{
		return idPlanPago;
	}

	/**
	 * Method 'setIdPlanPago'
	 * 
	 * @param idPlanPago
	 */
	public void setIdPlanPago(long idPlanPago)
	{
		this.idPlanPago = idPlanPago;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PlanPago)) {
			return false;
		}
		
		final PlanPago _cast = (PlanPago) _other;
		if (idPlanPago != _cast.idPlanPago) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idPlanPago ^ (idPlanPago >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PlanPagoPk
	 */
	public PlanPagoPk createPk()
	{
		return new PlanPagoPk(idPlanPago);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.PlanPago: " );
		ret.append( "idPlanPago=" + idPlanPago );
		ret.append( ", nombre=" + nombre );
		return ret.toString();
	}

}
