/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import com.Abogados.Lex.dao.*;
import com.Abogados.Lex.factory.*;
import com.Abogados.Lex.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class PresupuestoDetalles implements Serializable
{
	/** 
	 * This attribute maps to the column ID_DETALLE_PRESUPUESTO in the PRESUPUESTO_DETALLES table.
	 */
	protected long idDetallePresupuesto;

	/** 
	 * This attribute maps to the column SERVICIO in the PRESUPUESTO_DETALLES table.
	 */
	protected String servicio;

	/** 
	 * This attribute maps to the column MONTO in the PRESUPUESTO_DETALLES table.
	 */
	protected long monto;

	/**
	 * Method 'PresupuestoDetalles'
	 * 
	 */
	public PresupuestoDetalles()
	{
	}

	/**
	 * Method 'getIdDetallePresupuesto'
	 * 
	 * @return long
	 */
	public long getIdDetallePresupuesto()
	{
		return idDetallePresupuesto;
	}

	/**
	 * Method 'setIdDetallePresupuesto'
	 * 
	 * @param idDetallePresupuesto
	 */
	public void setIdDetallePresupuesto(long idDetallePresupuesto)
	{
		this.idDetallePresupuesto = idDetallePresupuesto;
	}

	/**
	 * Method 'getServicio'
	 * 
	 * @return String
	 */
	public String getServicio()
	{
		return servicio;
	}

	/**
	 * Method 'setServicio'
	 * 
	 * @param servicio
	 */
	public void setServicio(String servicio)
	{
		this.servicio = servicio;
	}

	/**
	 * Method 'getMonto'
	 * 
	 * @return long
	 */
	public long getMonto()
	{
		return monto;
	}

	/**
	 * Method 'setMonto'
	 * 
	 * @param monto
	 */
	public void setMonto(long monto)
	{
		this.monto = monto;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PresupuestoDetalles)) {
			return false;
		}
		
		final PresupuestoDetalles _cast = (PresupuestoDetalles) _other;
		if (idDetallePresupuesto != _cast.idDetallePresupuesto) {
			return false;
		}
		
		if (servicio == null ? _cast.servicio != servicio : !servicio.equals( _cast.servicio )) {
			return false;
		}
		
		if (monto != _cast.monto) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idDetallePresupuesto ^ (idDetallePresupuesto >>> 32));
		if (servicio != null) {
			_hashCode = 29 * _hashCode + servicio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (monto ^ (monto >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PresupuestoDetallesPk
	 */
	public PresupuestoDetallesPk createPk()
	{
		return new PresupuestoDetallesPk(idDetallePresupuesto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.PresupuestoDetalles: " );
		ret.append( "idDetallePresupuesto=" + idDetallePresupuesto );
		ret.append( ", servicio=" + servicio );
		ret.append( ", monto=" + monto );
		return ret.toString();
	}

}
