/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PRESUPUESTO_DETALLES table.
 */
public class PresupuestoDetallesPk implements Serializable
{
	protected long idDetallePresupuesto;

	/** 
	 * This attribute represents whether the primitive attribute idDetallePresupuesto is null.
	 */
	protected boolean idDetallePresupuestoNull;

	/** 
	 * Sets the value of idDetallePresupuesto
	 */
	public void setIdDetallePresupuesto(long idDetallePresupuesto)
	{
		this.idDetallePresupuesto = idDetallePresupuesto;
	}

	/** 
	 * Gets the value of idDetallePresupuesto
	 */
	public long getIdDetallePresupuesto()
	{
		return idDetallePresupuesto;
	}

	/**
	 * Method 'PresupuestoDetallesPk'
	 * 
	 */
	public PresupuestoDetallesPk()
	{
	}

	/**
	 * Method 'PresupuestoDetallesPk'
	 * 
	 * @param idDetallePresupuesto
	 */
	public PresupuestoDetallesPk(final long idDetallePresupuesto)
	{
		this.idDetallePresupuesto = idDetallePresupuesto;
	}

	/** 
	 * Sets the value of idDetallePresupuestoNull
	 */
	public void setIdDetallePresupuestoNull(boolean idDetallePresupuestoNull)
	{
		this.idDetallePresupuestoNull = idDetallePresupuestoNull;
	}

	/** 
	 * Gets the value of idDetallePresupuestoNull
	 */
	public boolean isIdDetallePresupuestoNull()
	{
		return idDetallePresupuestoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PresupuestoDetallesPk)) {
			return false;
		}
		
		final PresupuestoDetallesPk _cast = (PresupuestoDetallesPk) _other;
		if (idDetallePresupuesto != _cast.idDetallePresupuesto) {
			return false;
		}
		
		if (idDetallePresupuestoNull != _cast.idDetallePresupuestoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idDetallePresupuesto ^ (idDetallePresupuesto >>> 32));
		_hashCode = 29 * _hashCode + (idDetallePresupuestoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.Abogados.Lex.dto.PresupuestoDetallesPk: " );
		ret.append( "idDetallePresupuesto=" + idDetallePresupuesto );
		return ret.toString();
	}

}
