/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadAllCitasParam implements Serializable
{
	protected List CursorCitasList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorCitasList is null.
	 */
	protected boolean CursorCitasListNull = true;

	/**
	 * Method 'ReadAllCitasParam'
	 * 
	 */
	public ReadAllCitasParam()
	{
	}

	/**
	 * Method 'getCursorCitasList'
	 * 
	 * @return List
	 */
	public List getCursorCitasList()
	{
		return CursorCitasList;
	}

	/**
	 * Method 'setCursorCitasList'
	 * 
	 * @param CursorCitasList
	 */
	public void setCursorCitasList(List CursorCitasList)
	{
		this.CursorCitasList = CursorCitasList;
	}

	/** 
	 * Sets the value of CursorCitasListNull
	 */
	public void setCursorCitasListNull(boolean CursorCitasListNull)
	{
		this.CursorCitasListNull = CursorCitasListNull;
	}

	/** 
	 * Gets the value of CursorCitasListNull
	 */
	public boolean isCursorCitasListNull()
	{
		return CursorCitasListNull;
	}

	/**
	 * Method 'createCursorCitas'
	 * 
	 * @return ReadAllCitasParam.CursorCitas
	 */
	public ReadAllCitasParam.CursorCitas createCursorCitas()
	{
		return new ReadAllCitasParam.CursorCitas();
	}

	public class CursorCitas implements Serializable
	{
		/**
		 * Method 'CursorCitas'
		 * 
		 */
		public CursorCitas()
		{
		}

	}
}
