/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadAllCitasEstadosParam implements Serializable
{
	protected List CursorCitasEstadosList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorCitasEstadosList is null.
	 */
	protected boolean CursorCitasEstadosListNull = true;

	/**
	 * Method 'ReadAllCitasEstadosParam'
	 * 
	 */
	public ReadAllCitasEstadosParam()
	{
	}

	/**
	 * Method 'getCursorCitasEstadosList'
	 * 
	 * @return List
	 */
	public List getCursorCitasEstadosList()
	{
		return CursorCitasEstadosList;
	}

	/**
	 * Method 'setCursorCitasEstadosList'
	 * 
	 * @param CursorCitasEstadosList
	 */
	public void setCursorCitasEstadosList(List CursorCitasEstadosList)
	{
		this.CursorCitasEstadosList = CursorCitasEstadosList;
	}

	/** 
	 * Sets the value of CursorCitasEstadosListNull
	 */
	public void setCursorCitasEstadosListNull(boolean CursorCitasEstadosListNull)
	{
		this.CursorCitasEstadosListNull = CursorCitasEstadosListNull;
	}

	/** 
	 * Gets the value of CursorCitasEstadosListNull
	 */
	public boolean isCursorCitasEstadosListNull()
	{
		return CursorCitasEstadosListNull;
	}

	/**
	 * Method 'createCursorCitasEstados'
	 * 
	 * @return ReadAllCitasEstadosParam.CursorCitasEstados
	 */
	public ReadAllCitasEstadosParam.CursorCitasEstados createCursorCitasEstados()
	{
		return new ReadAllCitasEstadosParam.CursorCitasEstados();
	}

	public class CursorCitasEstados implements Serializable
	{
		/**
		 * Method 'CursorCitasEstados'
		 * 
		 */
		public CursorCitasEstados()
		{
		}

	}
}
