/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadAllSestadosParam implements Serializable
{
	protected List CursorSestadosList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorSestadosList is null.
	 */
	protected boolean CursorSestadosListNull = true;

	/**
	 * Method 'ReadAllSestadosParam'
	 * 
	 */
	public ReadAllSestadosParam()
	{
	}

	/**
	 * Method 'getCursorSestadosList'
	 * 
	 * @return List
	 */
	public List getCursorSestadosList()
	{
		return CursorSestadosList;
	}

	/**
	 * Method 'setCursorSestadosList'
	 * 
	 * @param CursorSestadosList
	 */
	public void setCursorSestadosList(List CursorSestadosList)
	{
		this.CursorSestadosList = CursorSestadosList;
	}

	/** 
	 * Sets the value of CursorSestadosListNull
	 */
	public void setCursorSestadosListNull(boolean CursorSestadosListNull)
	{
		this.CursorSestadosListNull = CursorSestadosListNull;
	}

	/** 
	 * Gets the value of CursorSestadosListNull
	 */
	public boolean isCursorSestadosListNull()
	{
		return CursorSestadosListNull;
	}

	/**
	 * Method 'createCursorSestados'
	 * 
	 * @return ReadAllSestadosParam.CursorSestados
	 */
	public ReadAllSestadosParam.CursorSestados createCursorSestados()
	{
		return new ReadAllSestadosParam.CursorSestados();
	}

	public class CursorSestados implements Serializable
	{
		/**
		 * Method 'CursorSestados'
		 * 
		 */
		public CursorSestados()
		{
		}

	}
}
