/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadCitaEstadoParam implements Serializable
{
	protected long vId;

	/** 
	 * This attribute represents whether the primitive attribute vId is null.
	 */
	protected boolean vIdNull = true;

	protected List CursorCitaEstadoList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorCitaEstadoList is null.
	 */
	protected boolean CursorCitaEstadoListNull = true;

	/**
	 * Method 'ReadCitaEstadoParam'
	 * 
	 */
	public ReadCitaEstadoParam()
	{
	}

	/**
	 * Method 'getVId'
	 * 
	 * @return long
	 */
	public long getVId()
	{
		return vId;
	}

	/**
	 * Method 'setVId'
	 * 
	 * @param vId
	 */
	public void setVId(long vId)
	{
		this.vId = vId;
	}

	/** 
	 * Sets the value of vIdNull
	 */
	public void setVIdNull(boolean vIdNull)
	{
		this.vIdNull = vIdNull;
	}

	/** 
	 * Gets the value of vIdNull
	 */
	public boolean isVIdNull()
	{
		return vIdNull;
	}

	/**
	 * Method 'getCursorCitaEstadoList'
	 * 
	 * @return List
	 */
	public List getCursorCitaEstadoList()
	{
		return CursorCitaEstadoList;
	}

	/**
	 * Method 'setCursorCitaEstadoList'
	 * 
	 * @param CursorCitaEstadoList
	 */
	public void setCursorCitaEstadoList(List CursorCitaEstadoList)
	{
		this.CursorCitaEstadoList = CursorCitaEstadoList;
	}

	/** 
	 * Sets the value of CursorCitaEstadoListNull
	 */
	public void setCursorCitaEstadoListNull(boolean CursorCitaEstadoListNull)
	{
		this.CursorCitaEstadoListNull = CursorCitaEstadoListNull;
	}

	/** 
	 * Gets the value of CursorCitaEstadoListNull
	 */
	public boolean isCursorCitaEstadoListNull()
	{
		return CursorCitaEstadoListNull;
	}

	/**
	 * Method 'createCursorCitaEstado'
	 * 
	 * @return ReadCitaEstadoParam.CursorCitaEstado
	 */
	public ReadCitaEstadoParam.CursorCitaEstado createCursorCitaEstado()
	{
		return new ReadCitaEstadoParam.CursorCitaEstado();
	}

	public class CursorCitaEstado implements Serializable
	{
		/**
		 * Method 'CursorCitaEstado'
		 * 
		 */
		public CursorCitaEstado()
		{
		}

	}
}
