/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadAllSolicitudesTiposParam implements Serializable
{
	protected List CursorSolicitudTiposList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorSolicitudTiposList is null.
	 */
	protected boolean CursorSolicitudTiposListNull = true;

	/**
	 * Method 'ReadAllSolicitudesTiposParam'
	 * 
	 */
	public ReadAllSolicitudesTiposParam()
	{
	}

	/**
	 * Method 'getCursorSolicitudTiposList'
	 * 
	 * @return List
	 */
	public List getCursorSolicitudTiposList()
	{
		return CursorSolicitudTiposList;
	}

	/**
	 * Method 'setCursorSolicitudTiposList'
	 * 
	 * @param CursorSolicitudTiposList
	 */
	public void setCursorSolicitudTiposList(List CursorSolicitudTiposList)
	{
		this.CursorSolicitudTiposList = CursorSolicitudTiposList;
	}

	/** 
	 * Sets the value of CursorSolicitudTiposListNull
	 */
	public void setCursorSolicitudTiposListNull(boolean CursorSolicitudTiposListNull)
	{
		this.CursorSolicitudTiposListNull = CursorSolicitudTiposListNull;
	}

	/** 
	 * Gets the value of CursorSolicitudTiposListNull
	 */
	public boolean isCursorSolicitudTiposListNull()
	{
		return CursorSolicitudTiposListNull;
	}

	/**
	 * Method 'createCursorSolicitudTipos'
	 * 
	 * @return ReadAllSolicitudesTiposParam.CursorSolicitudTipos
	 */
	public ReadAllSolicitudesTiposParam.CursorSolicitudTipos createCursorSolicitudTipos()
	{
		return new ReadAllSolicitudesTiposParam.CursorSolicitudTipos();
	}

	public class CursorSolicitudTipos implements Serializable
	{
		/**
		 * Method 'CursorSolicitudTipos'
		 * 
		 */
		public CursorSolicitudTipos()
		{
		}

	}
}
