/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadContratoParam implements Serializable
{
	protected long vId;

	/** 
	 * This attribute represents whether the primitive attribute vId is null.
	 */
	protected boolean vIdNull = true;

	protected List CursorContratoList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorContratoList is null.
	 */
	protected boolean CursorContratoListNull = true;

	/**
	 * Method 'ReadContratoParam'
	 * 
	 */
	public ReadContratoParam()
	{
	}

	/**
	 * Method 'getVId'
	 * 
	 * @return long
	 */
	public long getVId()
	{
		return vId;
	}

	/**
	 * Method 'setVId'
	 * 
	 * @param vId
	 */
	public void setVId(long vId)
	{
		this.vId = vId;
	}

	/** 
	 * Sets the value of vIdNull
	 */
	public void setVIdNull(boolean vIdNull)
	{
		this.vIdNull = vIdNull;
	}

	/** 
	 * Gets the value of vIdNull
	 */
	public boolean isVIdNull()
	{
		return vIdNull;
	}

	/**
	 * Method 'getCursorContratoList'
	 * 
	 * @return List
	 */
	public List getCursorContratoList()
	{
		return CursorContratoList;
	}

	/**
	 * Method 'setCursorContratoList'
	 * 
	 * @param CursorContratoList
	 */
	public void setCursorContratoList(List CursorContratoList)
	{
		this.CursorContratoList = CursorContratoList;
	}

	/** 
	 * Sets the value of CursorContratoListNull
	 */
	public void setCursorContratoListNull(boolean CursorContratoListNull)
	{
		this.CursorContratoListNull = CursorContratoListNull;
	}

	/** 
	 * Gets the value of CursorContratoListNull
	 */
	public boolean isCursorContratoListNull()
	{
		return CursorContratoListNull;
	}

	/**
	 * Method 'createCursorContrato'
	 * 
	 * @return ReadContratoParam.CursorContrato
	 */
	public ReadContratoParam.CursorContrato createCursorContrato()
	{
		return new ReadContratoParam.CursorContrato();
	}

	public class CursorContrato implements Serializable
	{
		/**
		 * Method 'CursorContrato'
		 * 
		 */
		public CursorContrato()
		{
		}

	}
}
