/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadAllContratosParam implements Serializable
{
	protected List CursorContratosList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorContratosList is null.
	 */
	protected boolean CursorContratosListNull = true;

	/**
	 * Method 'ReadAllContratosParam'
	 * 
	 */
	public ReadAllContratosParam()
	{
	}

	/**
	 * Method 'getCursorContratosList'
	 * 
	 * @return List
	 */
	public List getCursorContratosList()
	{
		return CursorContratosList;
	}

	/**
	 * Method 'setCursorContratosList'
	 * 
	 * @param CursorContratosList
	 */
	public void setCursorContratosList(List CursorContratosList)
	{
		this.CursorContratosList = CursorContratosList;
	}

	/** 
	 * Sets the value of CursorContratosListNull
	 */
	public void setCursorContratosListNull(boolean CursorContratosListNull)
	{
		this.CursorContratosListNull = CursorContratosListNull;
	}

	/** 
	 * Gets the value of CursorContratosListNull
	 */
	public boolean isCursorContratosListNull()
	{
		return CursorContratosListNull;
	}

	/**
	 * Method 'createCursorContratos'
	 * 
	 * @return ReadAllContratosParam.CursorContratos
	 */
	public ReadAllContratosParam.CursorContratos createCursorContratos()
	{
		return new ReadAllContratosParam.CursorContratos();
	}

	public class CursorContratos implements Serializable
	{
		/**
		 * Method 'CursorContratos'
		 * 
		 */
		public CursorContratos()
		{
		}

	}
}
