/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class ReadSestadoParam implements Serializable
{
	protected long vId;

	/** 
	 * This attribute represents whether the primitive attribute vId is null.
	 */
	protected boolean vIdNull = true;

	protected List CursorSestadoList = new ArrayList();

	/** 
	 * This attribute represents whether the primitive attribute CursorSestadoList is null.
	 */
	protected boolean CursorSestadoListNull = true;

	/**
	 * Method 'ReadSestadoParam'
	 * 
	 */
	public ReadSestadoParam()
	{
	}

	/**
	 * Method 'getVId'
	 * 
	 * @return long
	 */
	public long getVId()
	{
		return vId;
	}

	/**
	 * Method 'setVId'
	 * 
	 * @param vId
	 */
	public void setVId(long vId)
	{
		this.vId = vId;
	}

	/** 
	 * Sets the value of vIdNull
	 */
	public void setVIdNull(boolean vIdNull)
	{
		this.vIdNull = vIdNull;
	}

	/** 
	 * Gets the value of vIdNull
	 */
	public boolean isVIdNull()
	{
		return vIdNull;
	}

	/**
	 * Method 'getCursorSestadoList'
	 * 
	 * @return List
	 */
	public List getCursorSestadoList()
	{
		return CursorSestadoList;
	}

	/**
	 * Method 'setCursorSestadoList'
	 * 
	 * @param CursorSestadoList
	 */
	public void setCursorSestadoList(List CursorSestadoList)
	{
		this.CursorSestadoList = CursorSestadoList;
	}

	/** 
	 * Sets the value of CursorSestadoListNull
	 */
	public void setCursorSestadoListNull(boolean CursorSestadoListNull)
	{
		this.CursorSestadoListNull = CursorSestadoListNull;
	}

	/** 
	 * Gets the value of CursorSestadoListNull
	 */
	public boolean isCursorSestadoListNull()
	{
		return CursorSestadoListNull;
	}

	/**
	 * Method 'createCursorSestado'
	 * 
	 * @return ReadSestadoParam.CursorSestado
	 */
	public ReadSestadoParam.CursorSestado createCursorSestado()
	{
		return new ReadSestadoParam.CursorSestado();
	}

	public class CursorSestado implements Serializable
	{
		/**
		 * Method 'CursorSestado'
		 * 
		 */
		public CursorSestado()
		{
		}

	}
}
