/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UpdateCitasParam implements Serializable
{
	protected long vIdCita;

	/** 
	 * This attribute represents whether the primitive attribute vIdCita is null.
	 */
	protected boolean vIdCitaNull = true;

	protected java.util.Date vFechaHora;

	protected long vIdNotaria;

	/** 
	 * This attribute represents whether the primitive attribute vIdNotaria is null.
	 */
	protected boolean vIdNotariaNull = true;

	protected long vIdEstadoCita;

	/** 
	 * This attribute represents whether the primitive attribute vIdEstadoCita is null.
	 */
	protected boolean vIdEstadoCitaNull = true;

	protected int vSalida;

	/** 
	 * This attribute represents whether the primitive attribute vSalida is null.
	 */
	protected boolean vSalidaNull = true;

	/**
	 * Method 'UpdateCitasParam'
	 * 
	 */
	public UpdateCitasParam()
	{
	}

	/**
	 * Method 'getVIdCita'
	 * 
	 * @return long
	 */
	public long getVIdCita()
	{
		return vIdCita;
	}

	/**
	 * Method 'setVIdCita'
	 * 
	 * @param vIdCita
	 */
	public void setVIdCita(long vIdCita)
	{
		this.vIdCita = vIdCita;
	}

	/** 
	 * Sets the value of vIdCitaNull
	 */
	public void setVIdCitaNull(boolean vIdCitaNull)
	{
		this.vIdCitaNull = vIdCitaNull;
	}

	/** 
	 * Gets the value of vIdCitaNull
	 */
	public boolean isVIdCitaNull()
	{
		return vIdCitaNull;
	}

	/**
	 * Method 'getVFechaHora'
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getVFechaHora()
	{
		return vFechaHora;
	}

	/**
	 * Method 'setVFechaHora'
	 * 
	 * @param vFechaHora
	 */
	public void setVFechaHora(java.util.Date vFechaHora)
	{
		this.vFechaHora = vFechaHora;
	}

	/**
	 * Method 'getVIdNotaria'
	 * 
	 * @return long
	 */
	public long getVIdNotaria()
	{
		return vIdNotaria;
	}

	/**
	 * Method 'setVIdNotaria'
	 * 
	 * @param vIdNotaria
	 */
	public void setVIdNotaria(long vIdNotaria)
	{
		this.vIdNotaria = vIdNotaria;
	}

	/** 
	 * Sets the value of vIdNotariaNull
	 */
	public void setVIdNotariaNull(boolean vIdNotariaNull)
	{
		this.vIdNotariaNull = vIdNotariaNull;
	}

	/** 
	 * Gets the value of vIdNotariaNull
	 */
	public boolean isVIdNotariaNull()
	{
		return vIdNotariaNull;
	}

	/**
	 * Method 'getVIdEstadoCita'
	 * 
	 * @return long
	 */
	public long getVIdEstadoCita()
	{
		return vIdEstadoCita;
	}

	/**
	 * Method 'setVIdEstadoCita'
	 * 
	 * @param vIdEstadoCita
	 */
	public void setVIdEstadoCita(long vIdEstadoCita)
	{
		this.vIdEstadoCita = vIdEstadoCita;
	}

	/** 
	 * Sets the value of vIdEstadoCitaNull
	 */
	public void setVIdEstadoCitaNull(boolean vIdEstadoCitaNull)
	{
		this.vIdEstadoCitaNull = vIdEstadoCitaNull;
	}

	/** 
	 * Gets the value of vIdEstadoCitaNull
	 */
	public boolean isVIdEstadoCitaNull()
	{
		return vIdEstadoCitaNull;
	}

	/**
	 * Method 'getVSalida'
	 * 
	 * @return int
	 */
	public int getVSalida()
	{
		return vSalida;
	}

	/**
	 * Method 'setVSalida'
	 * 
	 * @param vSalida
	 */
	public void setVSalida(int vSalida)
	{
		this.vSalida = vSalida;
	}

	/** 
	 * Sets the value of vSalidaNull
	 */
	public void setVSalidaNull(boolean vSalidaNull)
	{
		this.vSalidaNull = vSalidaNull;
	}

	/** 
	 * Gets the value of vSalidaNull
	 */
	public boolean isVSalidaNull()
	{
		return vSalidaNull;
	}

}
