/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.Abogados.Lex.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UpdateContratoParam implements Serializable
{
	protected long vId;

	/** 
	 * This attribute represents whether the primitive attribute vId is null.
	 */
	protected boolean vIdNull = true;

	protected java.util.Date vFinicio;

	protected java.util.Date vFtermino;

	protected long vCestado;

	/** 
	 * This attribute represents whether the primitive attribute vCestado is null.
	 */
	protected boolean vCestadoNull = true;

	protected long vDcontrato;

	/** 
	 * This attribute represents whether the primitive attribute vDcontrato is null.
	 */
	protected boolean vDcontratoNull = true;

	protected long vPresupuesto;

	/** 
	 * This attribute represents whether the primitive attribute vPresupuesto is null.
	 */
	protected boolean vPresupuestoNull = true;

	protected long vAbogado;

	/** 
	 * This attribute represents whether the primitive attribute vAbogado is null.
	 */
	protected boolean vAbogadoNull = true;

	protected long vPpago;

	/** 
	 * This attribute represents whether the primitive attribute vPpago is null.
	 */
	protected boolean vPpagoNull = true;

	protected int vAabogado;

	/** 
	 * This attribute represents whether the primitive attribute vAabogado is null.
	 */
	protected boolean vAabogadoNull = true;

	protected int vAcliente;

	/** 
	 * This attribute represents whether the primitive attribute vAcliente is null.
	 */
	protected boolean vAclienteNull = true;

	protected long vFpago;

	/** 
	 * This attribute represents whether the primitive attribute vFpago is null.
	 */
	protected boolean vFpagoNull = true;

	protected int vSalida;

	/** 
	 * This attribute represents whether the primitive attribute vSalida is null.
	 */
	protected boolean vSalidaNull = true;

	/**
	 * Method 'UpdateContratoParam'
	 * 
	 */
	public UpdateContratoParam()
	{
	}

	/**
	 * Method 'getVId'
	 * 
	 * @return long
	 */
	public long getVId()
	{
		return vId;
	}

	/**
	 * Method 'setVId'
	 * 
	 * @param vId
	 */
	public void setVId(long vId)
	{
		this.vId = vId;
	}

	/** 
	 * Sets the value of vIdNull
	 */
	public void setVIdNull(boolean vIdNull)
	{
		this.vIdNull = vIdNull;
	}

	/** 
	 * Gets the value of vIdNull
	 */
	public boolean isVIdNull()
	{
		return vIdNull;
	}

	/**
	 * Method 'getVFinicio'
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getVFinicio()
	{
		return vFinicio;
	}

	/**
	 * Method 'setVFinicio'
	 * 
	 * @param vFinicio
	 */
	public void setVFinicio(java.util.Date vFinicio)
	{
		this.vFinicio = vFinicio;
	}

	/**
	 * Method 'getVFtermino'
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getVFtermino()
	{
		return vFtermino;
	}

	/**
	 * Method 'setVFtermino'
	 * 
	 * @param vFtermino
	 */
	public void setVFtermino(java.util.Date vFtermino)
	{
		this.vFtermino = vFtermino;
	}

	/**
	 * Method 'getVCestado'
	 * 
	 * @return long
	 */
	public long getVCestado()
	{
		return vCestado;
	}

	/**
	 * Method 'setVCestado'
	 * 
	 * @param vCestado
	 */
	public void setVCestado(long vCestado)
	{
		this.vCestado = vCestado;
	}

	/** 
	 * Sets the value of vCestadoNull
	 */
	public void setVCestadoNull(boolean vCestadoNull)
	{
		this.vCestadoNull = vCestadoNull;
	}

	/** 
	 * Gets the value of vCestadoNull
	 */
	public boolean isVCestadoNull()
	{
		return vCestadoNull;
	}

	/**
	 * Method 'getVDcontrato'
	 * 
	 * @return long
	 */
	public long getVDcontrato()
	{
		return vDcontrato;
	}

	/**
	 * Method 'setVDcontrato'
	 * 
	 * @param vDcontrato
	 */
	public void setVDcontrato(long vDcontrato)
	{
		this.vDcontrato = vDcontrato;
	}

	/** 
	 * Sets the value of vDcontratoNull
	 */
	public void setVDcontratoNull(boolean vDcontratoNull)
	{
		this.vDcontratoNull = vDcontratoNull;
	}

	/** 
	 * Gets the value of vDcontratoNull
	 */
	public boolean isVDcontratoNull()
	{
		return vDcontratoNull;
	}

	/**
	 * Method 'getVPresupuesto'
	 * 
	 * @return long
	 */
	public long getVPresupuesto()
	{
		return vPresupuesto;
	}

	/**
	 * Method 'setVPresupuesto'
	 * 
	 * @param vPresupuesto
	 */
	public void setVPresupuesto(long vPresupuesto)
	{
		this.vPresupuesto = vPresupuesto;
	}

	/** 
	 * Sets the value of vPresupuestoNull
	 */
	public void setVPresupuestoNull(boolean vPresupuestoNull)
	{
		this.vPresupuestoNull = vPresupuestoNull;
	}

	/** 
	 * Gets the value of vPresupuestoNull
	 */
	public boolean isVPresupuestoNull()
	{
		return vPresupuestoNull;
	}

	/**
	 * Method 'getVAbogado'
	 * 
	 * @return long
	 */
	public long getVAbogado()
	{
		return vAbogado;
	}

	/**
	 * Method 'setVAbogado'
	 * 
	 * @param vAbogado
	 */
	public void setVAbogado(long vAbogado)
	{
		this.vAbogado = vAbogado;
	}

	/** 
	 * Sets the value of vAbogadoNull
	 */
	public void setVAbogadoNull(boolean vAbogadoNull)
	{
		this.vAbogadoNull = vAbogadoNull;
	}

	/** 
	 * Gets the value of vAbogadoNull
	 */
	public boolean isVAbogadoNull()
	{
		return vAbogadoNull;
	}

	/**
	 * Method 'getVPpago'
	 * 
	 * @return long
	 */
	public long getVPpago()
	{
		return vPpago;
	}

	/**
	 * Method 'setVPpago'
	 * 
	 * @param vPpago
	 */
	public void setVPpago(long vPpago)
	{
		this.vPpago = vPpago;
	}

	/** 
	 * Sets the value of vPpagoNull
	 */
	public void setVPpagoNull(boolean vPpagoNull)
	{
		this.vPpagoNull = vPpagoNull;
	}

	/** 
	 * Gets the value of vPpagoNull
	 */
	public boolean isVPpagoNull()
	{
		return vPpagoNull;
	}

	/**
	 * Method 'getVAabogado'
	 * 
	 * @return int
	 */
	public int getVAabogado()
	{
		return vAabogado;
	}

	/**
	 * Method 'setVAabogado'
	 * 
	 * @param vAabogado
	 */
	public void setVAabogado(int vAabogado)
	{
		this.vAabogado = vAabogado;
	}

	/** 
	 * Sets the value of vAabogadoNull
	 */
	public void setVAabogadoNull(boolean vAabogadoNull)
	{
		this.vAabogadoNull = vAabogadoNull;
	}

	/** 
	 * Gets the value of vAabogadoNull
	 */
	public boolean isVAabogadoNull()
	{
		return vAabogadoNull;
	}

	/**
	 * Method 'getVAcliente'
	 * 
	 * @return int
	 */
	public int getVAcliente()
	{
		return vAcliente;
	}

	/**
	 * Method 'setVAcliente'
	 * 
	 * @param vAcliente
	 */
	public void setVAcliente(int vAcliente)
	{
		this.vAcliente = vAcliente;
	}

	/** 
	 * Sets the value of vAclienteNull
	 */
	public void setVAclienteNull(boolean vAclienteNull)
	{
		this.vAclienteNull = vAclienteNull;
	}

	/** 
	 * Gets the value of vAclienteNull
	 */
	public boolean isVAclienteNull()
	{
		return vAclienteNull;
	}

	/**
	 * Method 'getVFpago'
	 * 
	 * @return long
	 */
	public long getVFpago()
	{
		return vFpago;
	}

	/**
	 * Method 'setVFpago'
	 * 
	 * @param vFpago
	 */
	public void setVFpago(long vFpago)
	{
		this.vFpago = vFpago;
	}

	/** 
	 * Sets the value of vFpagoNull
	 */
	public void setVFpagoNull(boolean vFpagoNull)
	{
		this.vFpagoNull = vFpagoNull;
	}

	/** 
	 * Gets the value of vFpagoNull
	 */
	public boolean isVFpagoNull()
	{
		return vFpagoNull;
	}

	/**
	 * Method 'getVSalida'
	 * 
	 * @return int
	 */
	public int getVSalida()
	{
		return vSalida;
	}

	/**
	 * Method 'setVSalida'
	 * 
	 * @param vSalida
	 */
	public void setVSalida(int vSalida)
	{
		this.vSalida = vSalida;
	}

	/** 
	 * Sets the value of vSalidaNull
	 */
	public void setVSalidaNull(boolean vSalidaNull)
	{
		this.vSalidaNull = vSalidaNull;
	}

	/** 
	 * Gets the value of vSalidaNull
	 */
	public boolean isVSalidaNull()
	{
		return vSalidaNull;
	}

}
